### ISSUE TITLE
function run causes aws-sdk error 'ConfigError: Missing region in config'

### ISSUE THREAD

**Issue by theburningmonk** [serverless/serverless#1029]
When I run `sls function run myFunction -s dev -r eu-west-1` I get the following error:

```
 [ConfigError: Missing region in config]
  message: 'Missing region in config',
  code: 'ConfigError',
  time: Tue Apr 19 2016 13:41:21 GMT+0100 (BST) } 'ConfigError: Missing region in config\n ...
```

I can work around it by specifying the region in my code:

```
let AWS = require('aws-sdk');
AWS.config.update({region:'us-east-1'});
```

but that's not going to work when we go multi-region.

**Comment by c-knowles** [comment]
I ran into the same thing. I think the root cause is the AWS JavaScript SDK not setting a region by default. See [here](http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-configuring.html), specifically `The AWS SDK for Node.js doesn't select the region by default`. Maybe sls could set the region according to the CLI argument of `function run`?

Note, the region will be set when you deploy to Lambda it is only not set locally.  As a workaround I did this which works both locally and when deployed:
```
// set region if not set (as not set by the SDK by default)
if (!AWS.config.region) {
  AWS.config.update({
    region: 'eu-west-1'
  });
}
```

**Comment by theburningmonk** [comment]
I think the `sls function run` command should set the region for you (if aws-sdk package is installed), otherwise anyone who depends on aws-sdk in their function would need to do this in order to run their function locally.

**Comment by theburningmonk** [comment]
@c-knowles reckon something like this would work? for [nodejs](https://github.com/theburningmonk/serverless/blob/master/lib/RuntimeNode.js#L59-L65) and [nodejs4.3](https://github.com/theburningmonk/serverless/blob/master/lib/RuntimeNode43.js#L65-L71)

**Comment by c-knowles** [comment]
From my own experience of this, I would say it would be useful. So wait for one of the main maintainers to comment and/or submit a pull request for the change.

**Comment by theburningmonk** [comment]
@c-knowles 👍

**Comment by eahefnawy** [comment]
@theburningmonk I just checked your code. I feel that there's a cleaner way to solve it without using try/catch blocks. I'm gonna look into it and try to figure it out asap! 😊

**Comment by theburningmonk** [comment]
@eahefnawy thank you! :-)

**Comment by eahefnawy** [comment]
hmmm I looked into it today but I'm not able to reproduce :/ ... it's working perfectly for me. is there any particular thing I need to do to reproduce?

**Comment by theburningmonk** [comment]
@eahefnawy in your handler code, you need to `require('aws-sdk')` and then make a call to any AWS service - dynamodb, lambda, etc. - in your handler code. Then when you use `sls function run` it throws the error. It happens in v0.5.5

**Comment by eahefnawy** [comment]
oh I see. Sorry, It seems that I misunderstood the issue. Hmmmm I'm not sure if the framework should set the region by default on function run though. What if the user wants to make a request to another region other than the one passed as an option? And if some user doesn't know that we set a region by default he might end up messing with critical data in the wrong region.

I think that the fact that you got this error message makes it clear that you need to explicitly choose a region for your code execution (this is different from the region you choose for code deployment/running, which is used by Serverless). We like to be explicit rather than messing with user data.

Just my two cents 😊 ... I'll wait for more feedback from the community on this one :)

**Comment by eahefnawy** [comment]
Btw a super workaround is to just add the `AWS_DEFAULT_REGION` env var ... which is added by default in the Lambda runtime, and that probably explains why the deployed version works.

Hope that makes sense 😊

**Comment by theburningmonk** [comment]
This happens even when you specify the stage and region, i.e. `sls function run -s dev -r eu-west-1`. Which accordingly to the [doc](http://docs.serverless.com/docs/function-run) should execute the deployed code but it also fails with the same missing region in config.

![image](https://cloud.githubusercontent.com/assets/546969/14864073/38f74cde-0cb0-11e6-9bfb-ca5e0f37b02e.png)

Am I wrong in assuming that this should work since I've specified what region to use?

I've tried a no. of permutations:

* in project folder:
  * `sls function run funcName`
  * `sls function run funcName -s dev`
  * `sls function run funcName -s dev -r eu-west-1`
  * `sls function run funcName -r eu-west-1`

* in function folder:
  * `sls function run` 
  * `sls function run -s dev`
  * `sls function run -s dev -r eu-west-1`
  * `sls function run -r eu-west-1`

got the same error every time...

Setting the `AWS_DEFAULT_REGION` would work, but that means I'd have to remember to keep changing that when my function is deployed in multiple regions.

Also, maybe I misunderstood the doc, but where I don't specify a `-s` shouldn't it run my code locally? In those cases I get a prompt asking me to pick a staging instead:

![image](https://cloud.githubusercontent.com/assets/546969/14864022/19328062-0cb0-11e6-869b-774d6dfbfb63.png)

Let me know if you want me to put together an example project to illustrate this. Appreciate I might have just misunderstood how `sls function run` is supposed to work, but I feel like I'm following the documentation and not getting the expected behaviour.

Thanks,

**Comment by eahefnawy** [comment]
ooooh @theburningmonk I'm really sorry! That's my bad. Yes you're right the docs are outdated 😞 ... The thing is, before v0.5.5 you didn't have to specify stage region when you want to run locally, but we made some changes in how we handle env vars, so now you're specifying stage/region just to know which env vars to use. I'm gonna update the docs today to reflect this.

Again, sorry about this one 😞

**Comment by theburningmonk** [comment]
I see.

But since we have to specify region already, it'll be nice for serverless to set the aws-sdk (whenever your handler depends on aws-sdk to work) region to that region too. Intuitively I'm expecting it to work, having to tell serverless the region once to load the right env vars and then another time to tell aws-sdk (either in code or by setting the `AWS_DEFAULT_REGION` env var) feels like an unnecessary burden on the caller and something that serverless should handle - it already does that everywhere else, deploy, logs, etc.

**Comment by eahefnawy** [comment]
hmmm but what if your code want to interact with another region other than the one serving env vars?

**Comment by c-knowles** [comment]
Presumably even if a default were set in the framework, it could still be overridden by the above code explicitly inside a lambda?

**Comment by c-knowles** [comment]
Oh by the way, the place I ran into this was when I was storing data to DynamoDB in a function and had to set the region directly in the code to get it to run locally. I suppose it was only unexpected as most of the other variables are set and it just works. I do wonder why AWS made that choice in their SDK.

**Comment by flomotlik** [comment]
Imho the correct way the tool should react:

* Use the region defined by the CLI parameter as the default parameter
* Leave it to the users code to override this in the code if you want to talk to other regions

This way we support the default expectation of users but you can of course still do something different.

**Comment by flomotlik** [comment]
This is implemented now in Serverless V1

**Comment by securityvoid** [comment]
Just to confirm, if in my serverless.yml I have:
`provider:
  name: aws
  stage: dev
  region: us-east-1`

Based on the feedback in this thread, I should *not* be receiving the error, "ConfigError: Missing region in config" message if I'm on serverless 1.2.1?

or is there somewhere else I should be setting the region?

**Comment by pmuens** [comment]
@securityvoid thanks for getting back.
Hmm. That's really strange. So your `serverless.yml` looks like this?

```yml
provider:
  name: aws
  stage: dev
  region: us-east-1
```

That should work w/o problems. Additionally you could try to use the `defaults` property and try again (`defaults` will be removed in v2 but should be around a little while):

```yml
defaults:
  stage: dev
  region: us-east-1
```

**Comment by securityvoid** [comment]
Correct, my serverless.yml looks like the example you posted. I was able to get around the issue by setting the environmental variable AWS_REGION, but again, based on this thread that shouldn't be needed.

I'll try "defaults" and let you know the results.

**Comment by pmuens** [comment]
@securityvoid thanks for the clarification and the instructions on how to solve this problem 👍 

I'll reopen this one as it seems to be a bug.

**Comment by securityvoid** [comment]
I still get the error when I set the defaults as you have listed.

**Comment by securityvoid** [comment]
If it helps any, I'm running the following project stock out-of-the-box:
https://github.com/laardee/serverless-authentication-boilerplate

Setting AWS_REGION in the .env, or as a full environmental variable works around the issue.

**Comment by lynnaloo** [comment]
I was getting this error with 1.4, but no longer in 1.5

**Comment by duanefields** [comment]
I have the same issue, when running offline I have to set `AWS_REGION` or I get a `Failure: Missing region in config` error

**Comment by pmuens** [comment]
Closing this for now since it should be fixes in the latest version.

Please let us know if this is still an issue and we'll reopen!

**Comment by nikshepsvn** [comment]
Still an issue for me!

**Comment by pmuens** [comment]
> Still an issue for me!

Thanks for commenting @nikshepsvn 👍 

Could you please provide some more information how we can reproduce this? What Serverless version are you using? etc.

Thanks in advance!

**Comment by kkpoon** [comment]
I have the same issue, even I test it in the AWS console by pressing the `Test` button

### Problem
I have my Lambda in Typescript, so I use webpack + ts-loader to compile a handler.js.
I didn't use serverless plugin for typescript. I just run `webpack` and run `sls deploy`

```yaml
package:
  include:
    - handler.js
```

### My Fix
I don't webpack it, I `tsc` compile the typescripts and upload the compiled `.js` and `node_modules`. it works.

```
package:
  include:
    - node_modules/**
    - *.js
```

**Comment by pmuens** [comment]
@kkpoon thanks for commenting! This might be related to a bug in the automatic dev dependency exclusion.

However we've fixed it recently and the bugfix is available with Serverless `v1.18.1`. So updating to `v1.18.1` should solve your problem.

**Comment by JuHwon** [comment]
im facing this error right now with my serverless-dynamodb-client.
im running serverless v1.27.3 and serverless-offline 3.25.0
when i set the env variable the error is gone.

i have set the region in my provider config in the serverless.yml file. 
is there anything i need to do? or is it a bug?

**Comment by mistersingh179** [comment]
`AWS_DEFAULT_REGION` doesn't do the trick, but `AWS_REGION` did it!

**Comment by chanmathew** [comment]
> `AWS_DEFAULT_REGION` doesn't do the trick, but `AWS_REGION` did it!

Thanks for this, I had to set this in my config file under custom -> settings as well.

**Comment by acidjazz** [comment]
Thiis is still broken, setting the env `AWS_REGION` is not really a fix, i would re-open this @pmuens

**Comment by rob-gonz** [comment]
Also experiencing this issue, @pmuens .  AWS_REGION setting is a work around but not a fix.

**Comment by doctor3397** [comment]
Setting  env variable `AWS_REGION` was also working for me

**Comment by gitcatrat** [comment]
Did all this in EC2 and I still get `Error [ConfigError]: Missing region in config`.

```js
import AWS from 'aws-sdk';
AWS.config.update({region:'eu-north-1'});
process.env.AWS_DEFAULT_REGION = 'eu-north-1';
process.env.AWS_REGION = 'eu-north-1';
```

**Comment by gitcatrat** [comment]
Figured it out!
```js
import AWS from 'aws-sdk';
import app from './app.js'; // entry point to whole app
AWS.config.update(/* ... */);
```

What's wrong here? 

JS/Node runs all module root level code once on application startup. Now, if you have this in any of your files:
```js
// in module/file root level
const client = new AWS.DynamoDB.DocumentClient();
// NOT in function you're calling later
function example () {
   const client = new AWS.DynamoDB.DocumentClient();
}
```

Client is instantiated when you do `import app from './app.js';`, which means that it happens before you set `config`.

**Possible solutions:**

1. Require your application code **after** configuration update.
```js
import AWS from 'aws-sdk';
AWS.config.update(/* ... */);
// NOTE: you can't use import, those are static and
// you can't run any code before `import` statement
const app = require('./app.js');
```
2. Do all your configuration on separate file.
```js
import aws from './aws.js'; // do it in this file!
import app from './app.js';
```

**Comment by lscott3** [comment]
I am experiencing this issue as well. I am currently running the `serverless-mocha-plugin` and attempting to get my tests to run locally.

The command I'm running is `sls invoke test`

If I add the env var `AWS_REGION` that works, but I was under the impression that setting it in the `serverless.yml` would make it where we didn't have to set the env var.

I should note that it doesn't cause my tests to fail just more of a warning message - at least for now.

Either way, it works for now and my terminal/console is happy.
