### ISSUE TITLE
CloudWatch Logs Lambda Permissions create circular dependency

### ISSUE THREAD

**Issue by brendangibat** [serverless/serverless#11869]
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Is the issue caused by a plugin?

- [X] It is not a plugin issue

### Are you using the latest v3 release?

- [X] Yes, I'm using the latest v3 release

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Serverless version 3.29.0 included the merge from https://github.com/serverless/serverless/pull/11788 with changes to:

`lib/plugins/aws/package/compile/events/cloud-watch-log.js`
On line 92 this was included: https://github.com/serverless/serverless/pull/11788/files#diff-7947b4d174bc2f0b06b35408b1d01f10e7fed97f903d028e0f97bcdd94d8a083R92

```(nodejs)
            const dependsOn = [
              lambdaPermissionLogicalId,
              _.get(functionObj.targetAlias, 'logicalId'),
            ].filter(Boolean);
```

Which is later used here:
https://github.com/serverless/serverless/pull/11788/files#diff-7947b4d174bc2f0b06b35408b1d01f10e7fed97f903d028e0f97bcdd94d8a083R115

```(nodejs)
           const permissionTemplate = `
            {
              "Type": "AWS::Lambda::Permission",
              ${dependsOn.length ? `"DependsOn": ${JSON.stringify(dependsOn)},` : ''}
```

(for clarity I am including the value generated for lambdaPermissionLogicalId:
```(nodejs)
        const lambdaPermissionLogicalId =
          this.provider.naming.getLambdaIotFleetProvisioningPermissionLogicalId(functionName);
```
)

This causes a `DependsOn` array to be introduced to the `*LambdaPermissionLogsSubscriptionFilterCloudWatchLog` `AWS::Lambda::Permission` resource with a dependency on itself.

Example from the CloudFormation generated:
```
"FunctionTestLambdaPermissionLogsSubscriptionFilterCloudWatchLog": {
"Type": "AWS::Lambda::Permission",
"DependsOn": [
"FunctionTestLambdaPermissionLogsSubscriptionFilterCloudWatchLog"
 ],
```

While this has been included because the CloudWatchLogsRules require the `DependsOn` (see https://github.com/serverless/serverless/blob/16dd286a1d8aa764003565bcd6d7334be290e9bf/lib/plugins/aws/package/compile/events/cloud-watch-log.js#L99 ), this `DependsOn` for the `permissionTemplate` should not includes the `lambdaPermissionLogicalId`, as that creates a circular reference to itself.

This causes deployments using 3.29.0 to fail during CloudFormation template upload and validation, preventing stack deployment.

### Service configuration (serverless.yml) content

```yaml
N/A
```

### Command name and used flags

N/A

### Command output

```shell
N/A
```

### Environment information

```shell
N/A
```

**Comment by medikoo** [comment]
Thanks for openning it's being addressed by https://github.com/serverless/serverless/pull/11864

**Comment by medikoo** [comment]
Unfortunately, work on #11864  was discontinued by the original maintainer. Is there anyone willing to finalize fix for this bug?

**Comment by rnielsen** [comment]
I can have a go.

**Comment by Zazcallabah** [comment]
This issue is currently blocking us from upgrading to v3. If it is not solved i would recommend removing the https://www.serverless.com/framework/docs/providers/aws/events/cloudwatch-log page from the documentation since the feature is currently unusable.

**Comment by JamesKyburz** [comment]
@Zazcallabah You can still upgrade to 3.28.1 which doesn't have this issue.

**Comment by Zazcallabah** [comment]
And if we do that we wont have a clear upgrade path forward until this is fixed. At least with v2 to v3 being a major version step up, I can be sure no one will run a general upgrade on all our dependencies "because its just a minor version, they should be compatible".

**Comment by Imaisen17** [comment]
@Zazcallabah @JamesKyburz  Did you find the solution? Or the way how to avoid this problem?
I have the same issue it would be great if you give me a hit how to solve it
Thanks
