### ISSUE TITLE
Ensure Lift works with Serverless Framework V.4

### ISSUE THREAD

**Issue by austencollins** [serverless/serverless#12571]
### Issue description

We recently discovered the [Lift](https://github.com/getlift/lift) plugin was affected by our rewrite of Serverless Framework Variable parsing in V.4, which we did to support fetching data from more sources. That rewrite broke custom variable resolution logic added by plugins. We're fixing this now.

**Comment by NicoHinderling** [comment]
@austencollins I think I'm getting this now as well: "Provider construct is not supported":

<img width="1129" alt="image" src="https://github.com/serverless/serverless/assets/9902528/ddc9b1b7-8d5b-4c76-9533-c7088dc2e185">

Guessing this is the same issue 🤔

**Comment by austencollins** [comment]
This should be resolved in [this release](https://github.com/serverless/serverless/releases/tag/v4.0.35). Lift should now work seamlessly with V4.

We'll continue to monitor and test support for this Plugin. Please let us know if any other issues arise.

**Comment by NicoHinderling** [comment]
@austencollins you guys are crushing it!

**Comment by austencollins** [comment]
Thanks @NicoHinderling. We're releasing several times a week now, and we have this awesome backlog of stuff. Very exciting times here.

Standing by to see if this works for you. Shout out to @czubocha for jumping on this.

**Comment by NicoHinderling** [comment]
> @austencollins you guys are crushing it!
> 
> Will test and let you know if my issue is resolved shortly

So of our backend services using serverless, only one used `serverless-lift` and it was by far our biggest one (1500 LoC serverless.yml). I had some issues with the `sharp` dependency

```
✖ Build failed with 1 error:
src/snapshots/compareWorker.ts:2:18: ERROR: Could not resolve "sharp"
ServerlessError3: Build failed with 1 error:
src/snapshots/compareWorker.ts:2:18: ERROR: Could not resolve "sharp"
    at Esbuild._build (file:///Users/nicolashinderling/.serverless/releases/4.0.37/package/dist/sf-core.js:802:41463)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async before:package:createDeploymentArtifacts (file:///Users/nicolashinderling/.serverless/releases/4.0.37/package/dist/sf-core.js:802:34319)
    at async PluginManager.runHooks (file:///Users/nicolashinderling/.serverless/releases/4.0.37/package/dist/sf-core.js:1035:9290)
    at async PluginManager.invoke (file:///Users/nicolashinderling/.serverless/releases/4.0.37/package/dist/sf-core.js:1035:9997)
    at async PluginManager.run (file:///Users/nicolashinderling/.serverless/releases/4.0.37/package/dist/sf-core.js:1035:10779)
    at async Serverless.run (file:///Users/nicolashinderling/.serverless/releases/4.0.37/package/dist/sf-core.js:1042:10443)
    at async runFramework (file:///Users/nicolashinderling/.serverless/releases/4.0.37/package/dist/sf-core.js:1065:3180)
    at async route (file:///Users/nicolashinderling/.serverless/releases/4.0.37/package/dist/sf-core.js:1068:3074)
    at async Object.run2 [as run] (file:///Users/nicolashinderling/.serverless/releases/4.0.37/package/dist/sf-core.js:1068:4620)
    at async Object.handler (file:///Users/nicolashinderling/.serverless/releases/4.0.37/package/dist/sf-core.js:1068:9339)
```

But curiously removing the dep , installing, and then adding it back and installing again allowed my `npx sls package` command to succeed.

I noticed the packaging time went from ~66s down to ~17s 👍 

We currently don't deploy the packages individually, and one big difference is that our zip file went from 55MB to 173MB 👀  This must be because each JS file is now containing the bundled lib code and there's lots of files (and sourcemaps now too).

I think we could either:
1.  enable `individually: true` (which yielded zip files, none of which exceeded 11MB)
2. use either the `external` or `packages` fields for esbuild to have the big packages excluded from the bundle and then include them via package.patterns (which _I think_ should work, but am currently testing atm)

Leaning towards #1 but testing #2

**Comment by NicoHinderling** [comment]
Just kidding, I think approach #2 is not nearly as straightforward as I had hoped because of how child dependencies work. (ex. Auth0 might be removed from the bundle and then its included via `packages.patterns` but if a dependency of IT isn't included, it still doesn't work (in this case `rest-facade`))

<img width="1149" alt="image" src="https://github.com/serverless/serverless/assets/9902528/5ac40455-4069-4028-a03c-efe7f56f50e3">


@austencollins This is no longer relevant to this issue specifically, but I do have a question. [The description](https://www.serverless.com/framework/docs/providers/aws/guide/building) for "external" makes it sound like the node module set to external would not be bundled but **would** still be included

From my testing, that's not been the case. Setting a dependency (ex. auth0) to be "external" does in fact remove the auth0 code from being inlined in the bundle process, but it doesn't actually then include it in the `node_modules` directory

The only way I've gotten packages to still show up in the `node_modules` dir of the zipped build is by having to explicitly include it via `packages.patterns`. I suspect that's not the desired behavior, but I'm not sure.. could you shed some light on this?

**Comment by diestrin** [comment]
I'm still getting this error `Provider construct is not supported` with 
```JSON
"serverless": "4.1.23",
"serverless-lift": "1.29.0",
```

**Comment by czubocha** [comment]
Hey @diestrin, could you share more details so we can take a closer look at your specific case? How do you use `${construct}` in `serverless.yml`?

**Comment by diestrin** [comment]
Sure @czubocha. I use lift to create some queues and bucket for me, and then I call the reference for the environment variables of the lambda functions. Here's an example:

```yaml
environment:
  MATCHER_QUEUE_URL: ${env:MATCHER_QUEUE_URL, construct:matcher.queueUrl}
```
