### ISSUE TITLE
[V4] Typescript with ESM support

### ISSUE THREAD

**Issue by gdlin** [serverless/serverless#12706]
### Issue description

I've created a test project using typescript. If I don't enable ESM support, everything is working fine. I need ESM, so I've added `"type": "module"` to my `package.json` file.

After doing that, I have problems when executing the code locally, while the deployment works fine. I understand that _esbuild_ is not being used locally, from what I've read _ts-node_ is being used. Is there any way to replace that with _tsx_? I've had way better results with that. I'm fine using either, as long as ESM is supported.

The code:
```
export const hello = async (event: any) => {
  return {
    statusCode: 200,
    body: JSON.stringify({
      message: "Go Serverless v4! Your function executed successfully!",
    }),
  };
};
```

- When running `serverless invoke -f hello` (after deploying):
```
{
    "statusCode": 200,
    "body": "{\"message\":\"Go Serverless v4! Your function executed successfully!\"}"
}
```

- When running `serverless invoke local -f hello`:
```
✖ ReferenceError: module is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/home/gus/Projects/test/.serverless/build/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///home/gus/Projects/test/.serverless/build/handler.js:24:1
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadModule (file:///home/gus/.serverless/releases/4.1.16/package/dist/sf-core.js:851:9938)
    at async AwsInvokeLocal.invokeLocalNodeJs (file:///home/gus/.serverless/releases/4.1.16/package/dist/sf-core.js:851:9253)
    at async PluginManager.runHooks (file:///home/gus/.serverless/releases/4.1.16/package/dist/sf-core.js:854:9296)
    at async PluginManager.invoke (file:///home/gus/.serverless/releases/4.1.16/package/dist/sf-core.js:854:10066)
    at async PluginManager.run (file:///home/gus/.serverless/releases/4.1.16/package/dist/sf-core.js:854:10790)
    at async Serverless.run (file:///home/gus/.serverless/releases/4.1.16/package/dist/sf-core.js:861:10442)
    at async runFramework (file:///home/gus/.serverless/releases/4.1.16/package/dist/sf-core.js:909:2314)


✖ Exception encountered when loading /home/gus/Projects/test/.serverless/build/handler
ServerlessError2: Exception encountered when loading /home/gus/Projects/test/.serverless/build/handler
    at AwsInvokeLocal.invokeLocalNodeJs (file:///home/gus/.serverless/releases/4.1.16/package/dist/sf-core.js:851:9362)
    at async PluginManager.runHooks (file:///home/gus/.serverless/releases/4.1.16/package/dist/sf-core.js:854:9296)
    at async PluginManager.invoke (file:///home/gus/.serverless/releases/4.1.16/package/dist/sf-core.js:854:10066)
    at async PluginManager.run (file:///home/gus/.serverless/releases/4.1.16/package/dist/sf-core.js:854:10790)
    at async Serverless.run (file:///home/gus/.serverless/releases/4.1.16/package/dist/sf-core.js:861:10442)
    at async runFramework (file:///home/gus/.serverless/releases/4.1.16/package/dist/sf-core.js:909:2314)
    at async route (file:///home/gus/.serverless/releases/4.1.16/package/dist/sf-core.js:920:16046)
    at async Object.run2 [as run] (file:///home/gus/.serverless/releases/4.1.16/package/dist/sf-core.js:920:16444)
    at async run3 (file:///home/gus/.serverless/releases/4.1.16/package/dist/sf-core.js:920:17704)
```

- When running `serverless run dev` (after deploying, I call the endpoint):
```
→ λ hello ── aws:apigateway:v2:get:/
─ ReferenceError: module is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/home/gus/Projects/test/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///home/gus/Projects/test/.serverless/build/handler.js:24:1
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async importFunction (file:///home/gus/.serverless/releases/4.1.16/package/lib/plugins/aws/dev/local-lambda/runtime-wrappers/node.js:116:28)
    at async file:///home/gus/.serverless/releases/4.1.16/package/lib/plugins/aws/dev/local-lambda/runtime-wrappers/node.js:185:21
← λ hello
```

I'd appreciate any help. Thanks in advance.

### Context

# Service Overview
- Serverless Framework Version: 4.1.16
- Service Path: /home/gus/Projects/test
- Service Config File: serverless.yml
- Service Name: test
- Service App: test
- Service Runtime: nodejs20.x
- Service Stage: dev
- Service Region: us-east-1
- Command: invoke --function hello

## Service Config
```
# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: gdlin
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: test
# "service" is the name of this project. This will also be added to your AWS resource names.
service: test
provider:
  name: aws
  runtime: nodejs20.x
  profile: test
functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
```

**Comment by eahefnawy** [comment]
@gdlin You should be able to use ESM just by setting the `type: module` and serverless won't build in that case (since Node 20 supports ESM out of the box), but because you use TypeScript, **we have to build with esbuild**. So this is actually only an issue in TypeScript, which makes me think that my PR might add to the confusion 🤔

**Comment by Mmarzex** [comment]
@gdlin The expected behavior is that you should be able to set type to `module`, this is a bug in our built in esbuild support. For right now you can follow @eahefnawy 's suggestion to allow things to work, but we will add a fix in the next release that correctly builds your code to `ESM` compliant JS if you have type set to `module`.

**Comment by gdlin** [comment]
@Mmarzex thanks for the clarification. I just wanted to state the fact that it seemed odd. I'll work without that setting for now until it's fixed, it's not a problem for me at all.

@eahefnawy maybe you can check if esbuild is enabled, or if a tsconfig.json was detected? but, it seems that the best path would be to wait for a definite fix in the next release and if anyone has the same problem as me, they can refer to this issue.

Please close this issue if needed. If I encounter another TS ESM problem, I'll let you know.

Thanks to both :smiley:

**Comment by bml1g12** [comment]
Thanks, ran into this exact issue today after upgrading to Node 20 with ESM; will remove "module" for now

**Comment by eahefnawy** [comment]
@gdlin Apologies, I thought we are meant to only output CJS. @Mmarzex is correct, I'll get that fixed.

**Comment by tom2strobl** [comment]
I'm still not sure if it's the correct way to do things, but a simple fix was including the package.json into the [package patterns argument](https://www.serverless.com/framework/docs/providers/aws/guide/packaging#patterns) to include it in every function like so:

```yaml
package:
  individually: true
  patterns:
    - package.json
```

this way there's a `package.json` present in every function package and lambda knows .js files are esm modules.

**Comment by tri-star** [comment]
@Mmarzex @eahefnawy 
I'm using Serverless Framework v4.4.6 with TypeScript + ESM.
Currently, when I deploy a Lambda function written in TypeScript, I encounter the following error(CloudWatchLog):

```
    "errorType": "Runtime.UserCodeSyntaxError",
    "errorMessage": "SyntaxError: Unexpected token 'export'",
```

The built JS file under the .serverless folder has the following content and is in ESM format, but the file name is .js.

```js
// src/handler.ts
var hello = async (event, _context) => {
  // ...
};
export {
  hello
};
//# sourceMappingURL=handler.js.map
```

From the error message, I believe the built JS file needs to have a .mjs extension. However, in the current implementation, the file extension is fixed to .js in several places, such as the following:
https://github.com/serverless/serverless/blob/73b3de8a6aeeedf942c1c6fc2314417c82f149b7/lib/plugins/esbuild/index.js#L594

To run the Lambda function in ESM format, I think it is necessary to distribute the extensions as .js or .mjs according to the type:module specification in package.json.

**Comment by patrickbdaly** [comment]
@eahefnawy any update on getting your PR merged? Looks like all comments have been resolved

**Comment by czubocha** [comment]
Hey folks, this is now released in [v4.4.8](https://github.com/serverless/serverless/releases/tag/v4.4.8.). Give it a try and let us know if you’re still experiencing any issues.

**Comment by patrickbdaly** [comment]
@eahefnawy @czubocha 

This did not work for me using v4.4.10. I still get `SyntaxError: Cannot use import statement outside a module`. My lambda function was deployed with a package.json that was an empty object. Manually adding `"type": "module"` in the AWS console and redeploying fixes the problem.

**Comment by eahefnawy** [comment]
@patrickbdaly could you provide more details about your setup? You still have to specify `"type": "module"`, that's what tells us to set the target to ES6.

**Comment by patrickbdaly** [comment]
@eahefnawy Yes, I have `"type": "module"` defined. Because I am using serverless compose, I even tried putting package.json in each of the services sub directories as well, but that didn't help. Am I missing something with my setup because I am using compose?

My way around it has been to go into `~/.serverless/releases/4.4.14/package/dist/sf-core.js` and change `.js` to `.mjs` in multiple places:

```
`${modulePath}.mjs` and `${handlerPath}.mjs`
```

Since it auto updates, I need to do it regularly, which is painful, but it works.

**Comment by eahefnawy** [comment]
@patrickbdaly could you please share your esbuild config in `serverless.yml`?

**Comment by patrickbdaly** [comment]
@eahefnawy This ended up being an obscure configuration issue with my environment. I will explain in case others hit this down the road.

I manage node using volta, and I still had an old v16 configuration installed despite defaulting to v20. v16 had a serverless v3 global package installed. My directory structure looks something like this:

```
/serviceA
    serverless.yml
/serviceB
    serverless.yml
node_modules
package.json
serverless-compose.yml
```

When running `sls` from the root directory, serverless v4 is used. When running either `sls invoke` or `sls deploy` in the subdirectory, for some reason it was using node 16 and serverless 3. Uninstalling node16 and serverless v3 solved the problem and I can now both invoke ESM typescript locally and deploy to Lambda correctly (Installing serverless v4 in each of the subdirectories would also work)

I appreciate your support and sorry for causing any confusion!
