### ISSUE TITLE
Support for filterRules in S3 events for v1 ?

### ISSUE THREAD

**Issue by gergderkson** [serverless/serverless#1873]
Is it possible to include filterRules in S3 events so we can specify suffix/prefix like we could in v0?

The docs for this feature in v0:
```
"name" : "myS3Event",
"type": "s3",
"config": {
  "bucket": "${testEventBucket}", // required! - bucket name
  "bucketEvents": ["s3:ObjectCreated:*"], // required! - an array of events that should trigger the lambda
  "filterRules" : [
      {
          "name" : "prefix | suffix",
          "value" : "STRING_VALUE"
      }
   ] // optional, specify prefix or suffix for S3 event source
}
```

**Comment by flomotlik** [comment]
@gergderkson you should already be able to do this via custom resources: https://github.com/serverless/serverless/blob/master/docs/guide/custom-provider-resources.md#adding-custom-provider-resources

Basically the different configs will be merged together so it should work. There is still an issue as S3 Names get a number added to them at the end which is a bug we need to resolve #1823

**Comment by gergderkson** [comment]
Thanks for this.

I'm not able to see how this would allow us to create the S3 events and point them to specific functions. Would you be able to point me in the right direction?

**Comment by flomotlik** [comment]
you create the S3 event through the event configuration. Those will be compiled into a CF template. Then in your resources section you can copy it over to add your resources Section to add the filter:

you can get the CF template by running `serverless deploy --noDeploy`

```
resources:
  Resources:
    mycustombucket0S3Event:
      Properties:
        NotificationConfiguration:
          LambdaConfigurations:
            - ....
```

I looked at the CF S3 docs but haven't figured out what the syntax needs to be for this to include filters. Could you look into the correct syntax? We might be able to add it directly into the S3 event or at least add docs how to make it work.

**Comment by pmuens** [comment]
@gergderkson could you also install the latest master version via `npm install serverless/serverless` as we've fixed a bug which causes that the generated CloudFormation template you'll get when you run `serverless deploy --noDeploy` includes wrong information (see this PR which has fixed it: https://github.com/serverless/serverless/pull/1881)

**Comment by bdruth** [comment]
@pmuens are the additional properties we can define via additional resource configurations stemming from [this](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html#cfn-s3-bucket-notification), [this](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-notificationconfig.html), and [this](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-notificationconfig-lambdaconfig.html)? Where the names of parameters from the serverless.yml match the CF S3 parameters in the links above?

**Comment by bdruth** [comment]
From what I can see, the below should be a valid configuration, but I'm seeing two issues. First, something isn't working as the ``cloudformation-template-update-stack.json`` isn't generated unless I remove everything below ``BucketName``. Second, I have no idea how to reference the function I'm creating - the docs want this to be the ARN, so it's not something I can hard-code, presumably.
```resources:
  Resources:
    drcwbtechunks:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: my-bucket-with-filters
        NotificationConfiguration:
          LambdaConfigurations:
            - Event: s3:ObjectCreated:Put
              Filter:
                S3Key:
                  Rules:
                    - Name: suffix
                      Value: .manifest.json
              Function: transcode```

**Comment by bdruth** [comment]
Maybe Fn::GetAtt would work here?

```
resources:
  Resources:
    myfilteredbucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: my-bucket-with-filters
        NotificationConfiguration:
          LambdaConfigurations:
            - Event: s3:ObjectCreated:Put
              Filter:
                S3Key:
                  Rules:
                    - Name: suffix
                      Value: .manifest.json
              Function:
                Fn::GetAtt:
                  - myfilteredbucket
                  - Arn
```

**Comment by bdruth** [comment]
So, while this "looks" right in the generated CF JSON, it's failing when I deploy. I am getting a ``Unable to validate the following destination configurations`` on bucket create, and even when I add an explicity ``DependsOn: myfunction`` it still happens (even though I see my lambda successfully created before the bucket create begins.

Any ideas?

**Comment by bdruth** [comment]
Oh, slick - I think I got it - now I understand why you had a strange name for your resource +``0S3Event``. I didn't have an s3 event defined in my config, as I thought I was wholly declaring it in the override, and that prevented the appropriate IAM role to be defined/used for the S3 bucket to be able to invoke ``myfunction``. I was able to get the stack to create successfully now!

```
    events:
      - s3: myfilteredbucket

resources:
  Resources:
    myfilteredbucket0S3Event:
      Type: AWS::S3::Bucket
      DependsOn: myfunction
      Properties:
        BucketName: my-bucket-with-filters
        NotificationConfiguration:
          LambdaConfigurations:
            - Event: s3:ObjectCreated:Put
              Filter:
                S3Key:
                  Rules:
                    - Name: suffix
                      Value: .manifest.json
              Function:
                Fn::GetAtt:
                  - myfunction
                  - Arn

**Comment by flomotlik** [comment]
Cool, @bdruth . We're also currently working on better naming in #1951 to make sure we have better naming and remove the number at the end of the bucket name

**Comment by medhoover** [comment]
It would be great to have the feature now that the naming issue is fixed. I'm using the same s3 bucket for all stages but with different prefixes for each event, setting s3 triggers by stage is not only possible by adding it in resources...

**Comment by flomotlik** [comment]
@medhoover Yup definitely like the feature. I've put a help-wanted label on it. I don't think we'll focus on it soon (as its already possible to do this through custom resources and I'm not sure how many people need this at the moment to be in core) but we're open to a contribution (although if somebody wants to contribute please comment here first to talk about the specific implementation you want to work on)

**Comment by medhoover** [comment]
Maybe I can help, it would be a pleasure to contribute 😄, as this feature seems clear to me.
For the specs I think we should follow the Filter syntax for the additional property:

```yml
functions:
  uploader:
    name: image-uploader
    handler: images/uploader.handler
    events:
      - s3:
          bucket: uploads
          event: s3:ObjectCreated:*
          rules:
            -  name:  prefix
               value:  images/
            -  name:  suffix
               value:  .jpg
            -  name:  suffix
               value: .png
```
The rules will be mapped to the Filter property as: 
```yml
              Filter:
                S3Key:
                  Rules:
                    - Name: prefix
                      Value: images/
                    - Name: suffix
                      Value: .jpg
                    - Name: suffix
                      Value: .png
```

**Comment by medhoover** [comment]
Or we can have a more direct syntax:
```yml
#serverless.yml
          rules:
            -  prefix:  images/
            -  suffix:  .jpg
            -  suffix:  .png
```
But this could require an additional key validation within the compileS3Events

**Comment by flomotlik** [comment]
@medhoover that proposal looks great, good to go from my side.

**Comment by pmuens** [comment]
Done with #2068 /cc @flomotlik

**Comment by michaelm88** [comment]
hi , could you help , how can i create an event for S3 bucket which already exists , i dont want to overwrite it
