### ISSUE TITLE
No Such Bucket

### ISSUE THREAD

**Issue by Savalas** [serverless/serverless#1877]
I am getting this error after attempting to sls deploy:  

No Such Bucket -----------------------------------------
 
     The specified bucket does not exist
 
     For debugging logs, run again after setting SLS_DEBUG env var.
 
  Stack Trace --------------------------------------------
 
NoSuchBucket: The specified bucket does not exist
    at Request.extractError (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/services/s3.js:524:35)
    at Request.callListeners (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:615:14)
    at Request.transition (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:617:12)
    at Request.callListeners (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:615:14)
    at Request.transition (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:38:9)
 

I have been searching all over for a way to "clean" my environment or any fix for this.  It has been very confusing because I saw some similar issues for 0.5  but I don't believe that they apply to V1 (For instance, removing the _meta folder- which I can not find).  The way that I got to this issue
is that I previously could not deploy my lambda functions- therefore I deleted my functions and then the buckets. How do I create these bucket the way serverless initially create them?

  Get Support --------------------------------------------
     Docs:          v1.docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
     Please report this error. We think it might be a bug.

Bug Report Template -----------------------------------------------

##### Stack-Trace (Optional):

Feature Request Template ------------------------------------------

##### Benefits:

* Benefit one...

##### Drawbacks:

* Drawback one...

##### Additional Details:

Discussion template  ----------------------------------------------

**Comment by sdruipeng** [comment]
I got the same issue.

I just run serverless create --template aws-nodejs and run serverless deploy.
I tried more than 5 times, every time  I got the Bucket error report

F:\LinkIt\aws\my-first-service>serverless deploy
Serverless: Zipping service...

  Serverless Error ---------------------------------------

     The specified bucket does not exist

  Get Support --------------------------------------------
     Docs:          v1.docs.serverless.com
     Bugs:

**Comment by flomotlik** [comment]
@Savalas @sdruipeng could you let us know what Cloudformation is saying? Especially the Events part and where its failing. Is it possible that you are not able to add the bucket for some reason due to the rights?

**Comment by sdruipeng** [comment]
@Savalas flomotlik

Thank you for you quick reply.

(1), suspected bug.
the failure to add the bucket is not due to the IAM rights, since I noticed that the S3 buckets can be added to my S3 when I use serverless 0.5.0 and 0.4.2. I had to switch to a higher version of serverless since I could not follow the tutorials available on youtube. I just got deployment errors when I use 0.4.2 and 0.5.0. But I noticed a nested S3 bucket was created when using 0.4.2 and 0.5.0.
The problem for me with 0.5.0 was I could not create the request templates and the reported errors were difficult to interpret.

Then I decided to update to 1.0.0Beta. The last version I tried is beta2. Beta2 has the same problem.
I used to Windows cmd and Git Bash too. I just run serverless create --template aws-nodejs and serverless deploy. I feel a little confused because the command was serverless dash deploy for older versions.  Actually, I tried both. I uninstalled the serverless beta 2 for more than 3 times and reinstall it to give it a fresh installation. I just got the error message, which implies that it is a bug and advice me to report it.

(2) cloudFormation
Thought I am not sure how to interpret the outputs, I saw fonts in orange and red colors.

```
	17:37:30 UTC+0800	UPDATE_ROLLBACK_COMPLETE	AWS::CloudFormation::Stack	aws-nodejs-dev	
Physical ID:arn:aws:cloudformation:us-east-1:446935793664:stack/aws-nodejs-dev/81fa9c00-61f7-11e6-983e-500c28b32ec6
17:37:29 UTC+0800	UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS	AWS::CloudFormation::Stack	aws-nodejs-dev	
Physical ID:arn:aws:cloudformation:us-east-1:446935793664:stack/aws-nodejs-dev/81fa9c00-61f7-11e6-983e-500c28b32ec6
17:37:27 UTC+0800	UPDATE_COMPLETE	AWS::Lambda::Function	hello	
Physical ID:aws-nodejs-dev-hello
17:37:02 UTC+0800	UPDATE_ROLLBACK_IN_PROGRESS	AWS::CloudFormation::Stack	aws-nodejs-dev	The following resource(s) failed to update: [hello].
Physical ID:arn:aws:cloudformation:us-east-1:446935793664:stack/aws-nodejs-dev/81fa9c00-61f7-11e6-983e-500c28b32ec6
17:37:01 UTC+0800	UPDATE_FAILED	AWS::Lambda::Function	hello	Function not found: arn:aws:lambda:us-east-1:446935793664:function:aws-nodejs-dev-hello
Physical ID:aws-nodejs-dev-hello
17:37:00 UTC+0800	UPDATE_IN_PROGRESS	AWS::Lambda::Function	hello	
17:36:55 UTC+0800	UPDATE_IN_PROGRESS	AWS::CloudFormation::Stack	aws-nodejs-dev	User Initiated
Physical ID:arn:aws:cloudformation:us-east-1:446935793664:stack/aws-nodejs-dev/81fa9c00-61f7-11e6-983e-500c28b32ec6
17:35:29 UTC+0800	UPDATE_ROLLBACK_COMPLETE	AWS::CloudFormation::Stack	aws-nodejs-dev	
Physical ID:arn:aws:cloudformation:us-east-1:446935793664:stack/aws-nodejs-dev/81fa9c00-61f7-11e6-983e-500c28b32ec6
17:35:27 UTC+0800	UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS	AWS::CloudFormation::Stack	aws-nodejs-dev	
Physical ID:arn:aws:cloudformation:us-east-1:446935793664:stack/aws-nodejs-dev/81fa9c00-61f7-11e6-983e-500c28b32ec6
17:35:26 UTC+0800	UPDATE_COMPLETE	AWS::Lambda::Function	hello	
Physical ID:aws-nodejs-dev-hello
17:35:08 UTC+0800	UPDATE_ROLLBACK_IN_PROGRESS	AWS::CloudFormation::Stack	aws-nodejs-dev	The following resource(s) failed to update: [hello].
Physical ID:arn:aws:cloudformation:us-east-1:446935793664:stack/aws-nodejs-dev/81fa9c00-61f7-11e6-983e-500c28b32ec6
17:35:05 UTC+0800	UPDATE_FAILED	AWS::Lambda::Function	hello	Function not found: arn:aws:lambda:us-east-1:446935793664:function:aws-nodejs-dev-hello
Physical ID:aws-nodejs-dev-hello
17:35:05 UTC+0800	UPDATE_IN_PROGRESS	AWS::Lambda::Function	hello	
Physical ID:aws-nodejs-dev-hello
17:34:59 UTC+0800	UPDATE_IN_PROGRESS	AWS::CloudFormation::Stack	aws-nodejs-dev	User Initiated
Physical ID:arn:aws:cloudformation:us-east-1:446935793664:stack/aws-nodejs-dev/81fa9c00-61f7-11e6-983e-500c28b32ec6
16:20:02 UTC+0800	UPDATE_COMPLETE	AWS::CloudFormation::Stack	aws-nodejs-dev	
16:20:00 UTC+0800	UPDATE_COMPLETE_CLEANUP_IN_PROGRESS	AWS::CloudFormation::Stack	aws-nodejs-dev	
Physical ID:arn:aws:cloudformation:us-east-1:446935793664:stack/aws-nodejs-dev/81fa9c00-61f7-11e6-983e-500c28b32ec6
```

**Comment by sdruipeng** [comment]
Serverless Framework Version:

1.0.0-beta.2

Operating System:

Win 10 in Chinese

Node.js

5.6.0 

![image](https://cloud.githubusercontent.com/assets/15041387/17738234/0d47459c-64c3-11e6-961d-6f2f14f32087.png)

 **cloudFormation**
Since I am new to serverless, especially on 1.0.0-beta.2, I don't know how to find the errors corresponding to 'serverless deploy'. 

![image](https://cloud.githubusercontent.com/assets/15041387/17738788/5d214cd2-64c5-11e6-95e6-59702cfc358e.png)

**Comment by Savalas** [comment]
@flomotlik  All the rights were there. I am using full admin rights. This occurred after I deleted the buckets from S3. I am new to AWS/Lambda and serverless so I may get some terminology/understanding wrong but this is what I have observed:  I wanted to change the name of the service from aws-nodejs to my custom name. Additionally, I wanted to change the region. After I made those changes then I received  and error that my functions could not be updated.  (after an sls deploy). So this is when I deleted the functions and the associated api-gateway. I went back to deploy and I still couldn't - so I thought that I could clean things up if I deleted the associated S3 buckets. After doing this, the above error arose.    


However, I was able to fix it this way. I created a new project with create and was able to deploy with a a new service name. I then went back to my old project and deployed functions to the newly created custom service. It appears that serverless (or something) is holding on the historical names of buckets etc.   Hope some of this helps--- it's working for me now.

**Comment by flomotlik** [comment]
@Savalas Yup that would clear up why the bucket isn't there after the deletion. Great that you were able to fix it.

**Comment by fny** [comment]
So I don't think this issue should be resolved unless @Savalas's work around is an expected behavior... and even still, the resulting error message is pretty bad.

If I delete a cloudformation associated with a serverless project and attempt to redeploy with that same project name, I see "The specified bucket does not exist".

In my opinion, you should be able to redeploy with the same name after you've wiped a stack.

**Comment by flomotlik** [comment]
@fny we're going to make this clearer in the documentation that if you go in and manually remove things there will be issues. While there are a few things we can do about this in the future (and we're already implementing a few features to make this easier) it would take a long time to thoroughly fix this for any situation and we'd rather invest that time to build more features and document this behaviour thoroughly.

**Comment by csjohn** [comment]
@flomotlik To be clear, does this mean that serverless expects _all_ operations on AWS resources to be done through the serverless CLI / app?

**Comment by rowanu** [comment]
@csjohn `sls` uses CloudFormation to manage its resources, and it's CFN which doesn't like it (understandably) if you "pull the rug out from under it". If you make changes via CFN it should work, regardless of wether you used `sls` to do it (or the AWS Console, or AWS CLI, etc).

**Comment by lindekaer** [comment]
I am running into this same issue, but it is unclear clear to me how to work around it.
When I go to my AWS console both S3, API Gateway and CloudFormation is completely empty.

My chain of actions:
- `git clone https://github.com/pmuens/serverless-book.git`
- `cd serveless-book/xx-code/todos/backend`
- `npm install`
- `sls deploy`

```
Then I get the error:

Serverless Error ---------------------------------------

     The specified bucket does not exist

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

  Your Environment Infomation -----------------------------
     OS:                 darwin
     Node Version:       6.5.0
     Serverless Version: 1.0.2
```

Can I somehow provide some any additional information?

**Comment by flomotlik** [comment]
@lindekaer can you try creating a project through the `serverless create` command and deploy that? Make sure the stack is completely removed from AWS first as well.

**Comment by lindekaer** [comment]
@flomotlik thx for your quick reply. I just tried creating and deploying a new project running:

`sls create --template aws-nodejs --path sls-test --name cool-service`
`cd sls-test`
`sls deploy`

This works, thanks! 

When you say *make sure stack is removed*, do you then mean to verify that I have no S3 buckets?

**Comment by flomotlik** [comment]
Sometimes during trials of Serverless when a stack is deployed and then changes are done in the AWS console follow up deployments fail. Thats why we suggest to simply remove the whole stack and redeploy to make sure nothing surprising happens.

**Comment by lindekaer** [comment]
@flomotlik I just have an update - I have just done the following actions leading to the same problem:

`sls deploy` (re-deploying an application)
```
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
```

From here it simply hangs forever. I then kill the process.
When trying to `sls deploy` again I get the error:

```
Serverless: Packaging service...

  Serverless Error ---------------------------------------

     The specified bucket does not exist

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues

  Your Environment Infomation -----------------------------
     OS:                 darwin
     Node Version:       6.5.0
     Serverless Version: 1.0.2
```

I hope I can avoid recreating the project every time this occurs.
Hope it can help as to what might be the issue!

**Comment by njeirath** [comment]
I had the exact same issue as @lindekaer and was able to get around the error by logging in to the AWS console and manually deleting the cloud formation for my service and rerunning the deploy command after that.  Hope that at least helps to get around the issue.

**Comment by str3tch** [comment]
I now have this same error.

I created my service originally with no problems. But I wanted to remove it and restart, so I did an `sls remove` which partially worked but failed because my S3 bucket was not empty. So I went through the AWS console and removed the bucket and removed the stack completely. Now I'm trying to deploy the service again, but I get this error:

```
    at Request.callListeners (C:\Users\chrisd\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\sequential_executor.js:105:20)                                                                                                                            
    at Request.emit (C:\Users\chrisd\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\sequential_executor.js:77:10)                                                                                                                                      
    at Request.emit (C:\Users\chrisd\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\request.js:668:14)                                                                                                                                                 
    at Request.transition (C:\Users\chrisd\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\request.js:22:10)                                                                                                                                            
    at AcceptorStateMachine.runTo (C:\Users\chrisd\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\state_machine.js:14:12)                                                                                                                              
    at C:\Users\chrisd\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\state_machine.js:26:10                                                                                                                                                           
    at Request.<anonymous> (C:\Users\chrisd\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\request.js:38:9)                                                                                                                                            
    at Request.<anonymous> (C:\Users\chrisd\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\request.js:670:12)                                                                                                                                          
    at Request.callListeners (C:\Users\chrisd\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\sequential_executor.js:115:18)                                                                                                                            
    at Request.emit (C:\Users\chrisd\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\sequential_executor.js:77:10)                                                                                                                                      
    at Request.emit (C:\Users\chrisd\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\request.js:668:14)                                                                                                                                                 
    at Request.transition (C:\Users\chrisd\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\request.js:22:10)                                                                                                                                            
    at AcceptorStateMachine.runTo (C:\Users\chrisd\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\state_machine.js:14:12)                                                                                                                              
    at C:\Users\chrisd\AppData\Roaming\npm\node_modules\serverless\node_modules\aws-sdk\lib\state_machine.js:26:10                                                                                                                                                           
                                                                                                                                                                                                                                                                             
  Get Support --------------------------------------------                                                                                                                                                                                                                   
     Docs:          docs.serverless.com                                                                                                                                                                                                                                      
     Bugs:          github.com/serverless/serverless/issues                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                             
  Your Environment Infomation -----------------------------                                                                                                                                                                                                                  
     OS:                 win32                                                                                                                                                                                                                                               
     Node Version:       4.4.3                                                                                                                                                                                                                                               
     Serverless Version: 1.0.2        
```

Thing is, this seems to be a serverless error and not a CFN one, as it hasn't even got to the stage of uploading anything to CFN.

I've been doing this before (removing the entire stack manually) and redeploying and it's worked. But not today 👎

**Comment by str3tch** [comment]
OK I've dug into the code and it could be a real bug.

When I did the `sls remove` it removed the deployment bucket for my service.

But now I am trying to `sls deploy` again, it is not recreating the deployment bucket. It's asking the AWS SDK to list the objects in the deployment bucket that got deleted.

See below for the comms to and from AWS. The bucket `uca-ux-sydney-serverlessdeploymentbucket-uryiscfknofg` does not exist, and this is causing the deploy to fail.

@flomotlik  How can I force serverless to create it's deployment bucket again?

```
Response {                                                                                                                                                                                                                                                                   
  request:                                                                                                                                                                                                                                                                   
   Request {                                                                                                                                                                                                                                                                 
     domain: null,                                                                                                                                                                                                                                                           
     service:                                                                                                                                                                                                                                                                
      Service {                                                                                                                                                                                                                                                              
        config: [Object],                                                                                                                                                                                                                                                    
        isGlobalEndpoint: false,                                                                                                                                                                                                                                             
        endpoint: [Object],                                                                                                                                                                                                                                                  
        _clientId: 3 },                                                                                                                                                                                                                                                      
     operation: 'listObjectsV2',                                                                                                                                                                                                                                             
     params:                                                                                                                                                                                                                                                                 
      { Bucket: 'uca-ux-sydney-serverlessdeploymentbucket-uryiscfknofg',                                                                                                                                                                                                     
        Prefix: 'serverless/uca-ux/sydney' },                                                                                                                                                                                                                                
     httpRequest:                                                                                                                                                                                                                                                            
      HttpRequest {                                                                                                                                                                                                                                                          
        method: 'GET',                                                                                                                                                                                                                                                       
        path: '/?list-type=2&prefix=serverless%2Fuca-ux%2Fsydney',                                                                                                                                                                                                           
        headers: [Object],                                                                                                                                                                                                                                                   
        body: '',                                                                                                                                                                                                                                                            
        endpoint: [Object],                                                                                                                                                                                                                                                  
        region: 'ap-southeast-2',                                                                                                                                                                                                                                            
        virtualHostedBucket: 'uca-ux-sydney-serverlessdeploymentbucket-uryiscfknofg',                                                                                                                                                                                        
        stream: [Object] },                                                                                                                                                                                                                                                  
     startTime: Thu Oct 20 2016 16:07:12 GMT+1100 (AUS Eastern Daylight Time),                                                                                                                                                                                               
     response: [Circular],                                                                                                                                                                                                                                                   
     _asm: AcceptorStateMachine { currentState: 'send', states: [Object] },                                                                                                                                                                                                  
     _haltHandlersOnError: false,                                                                                                                                                                                                                                            
     _events:                                                                                                                                                                                                                                                                
      { validate: [Object],                                                                                                                                                                                                                                                  
        afterBuild: [Object],                                                                                                                                                                                                                                                
        restart: [Object],                                                                                                                                                                                                                                                   
        sign: [Object],                                                                                                                                                                                                                                                      
        validateResponse: [Object],                                                                                                                                                                                                                                          
        send: [Object],                                                                                                                                                                                                                                                      
        httpHeaders: [Object],                                                                                                                                                                                                                                               
        httpData: [Object],                                                                                                                                                                                                                                                  
        httpDone: [Object],                                                                                                                                                                                                                                                  
        retry: [Object],                                                                                                                                                                                                                                                     
        afterRetry: [Object],                                                                                                                                                                                                                                                
        build: [Object],                                                                                                                                                                                                                                                     
        extractData: [Object],                                                                                                                                                                                                                                               
        extractError: [Object],                                                                                                                                                                                                                                              
        httpError: [Object],                                                                                                                                                                                                                                                 
        beforePresign: [Object],                                                                                                                                                                                                                                             
        complete: [Object] },                                                                                                                                                                                                                                                
     emit: [Function: emit],                                                                                                                                                                                                                                                 
     signedAt: Thu Oct 20 2016 16:07:12 GMT+1100 (AUS Eastern Daylight Time) },                                                                                                                                                                                              
  data: null,                                                                                                                                                                                                                                                                
  error: null,
Response {                                                                                                                                                                                                                                                                   
  request:                                                                                                                                                                                                                                                                   
   Request {                                                                                                                                                                                                                                                                 
     domain: null,                                                                                                                                                                                                                                                           
     service:                                                                                                                                                                                                                                                                
      Service {                                                                                                                                                                                                                                                              
        config: [Object],                                                                                                                                                                                                                                                    
        isGlobalEndpoint: false,                                                                                                                                                                                                                                             
        endpoint: [Object],                                                                                                                                                                                                                                                  
        _clientId: 3 },                                                                                                                                                                                                                                                      
     operation: 'listObjectsV2',                                                                                                                                                                                                                                             
     params:                                                                                                                                                                                                                                                                 
      { Bucket: 'uca-ux-sydney-serverlessdeploymentbucket-uryiscfknofg',                                                                                                                                                                                                     
        Prefix: 'serverless/uca-ux/sydney' },                                                                                                                                                                                                                                
     httpRequest:                                                                                                                                                                                                                                                            
      HttpRequest {                                                                                                                                                                                                                                                          
        method: 'GET',                                                                                                                                                                                                                                                       
        path: '/?list-type=2&prefix=serverless%2Fuca-ux%2Fsydney',                                                                                                                                                                                                           
        headers: [Object],                                                                                                                                                                                                                                                   
        body: '',                                                                                                                                                                                                                                                            
        endpoint: [Object],                                                                                                                                                                                                                                                  
        region: 'ap-southeast-2',                                                                                                                                                                                                                                            
        virtualHostedBucket: 'uca-ux-sydney-serverlessdeploymentbucket-uryiscfknofg',                                                                                                                                                                                        
        stream: [Object] },                                                                                                                                                                                                                                                  
     startTime: Thu Oct 20 2016 16:07:12 GMT+1100 (AUS Eastern Daylight Time),                                                                                                                                                                                               
     response: [Circular],                                                                                                                                                                                                                                                   
     _asm: AcceptorStateMachine { currentState: 'send', states: [Object] },                                                                                                                                                                                                  
     _haltHandlersOnError: false,                                                                                                                                                                                                                                            
     _events:                                                                                                                                                                                                                                                                
      { validate: [Object],                                                                                                                                                                                                                                                  
        afterBuild: [Object],                                                                                                                                                                                                                                                
        restart: [Object],                                                                                                                                                                                                                                                   
        sign: [Object],                                                                                                                                                                                                                                                      
        validateResponse: [Object],                                                                                                                                                                                                                                          
        send: [Object],                                                                                                                                                                                                                                                      
        httpHeaders: [Object],                                                                                                                                                                                                                                               
        httpData: [Object],                                                                                                                                                                                                                                                  
        httpDone: [Object],                                                                                                                                                                                                                                                  
        retry: [Object],                                                                                                                                                                                                                                                     
        afterRetry: [Object],                                                                                                                                                                                                                                                
        build: [Object],                                                                                                                                                                                                                                                     
        extractData: [Object],                                                                                                                                                                                                                                               
        extractError: [Object],                                                                                                                                                                                                                                              
        httpError: [Object],                                                                                                                                                                                                                                                 
        beforePresign: [Object],                                                                                                                                                                                                                                             
        complete: [Object] },                                                                                                                                                                                                                                                
     emit: [Function: emit],                                                                                                                                                                                                                                                 
     signedAt: Thu Oct 20 2016 16:07:12 GMT+1100 (AUS Eastern Daylight Time) },                                                                                                                                                                                              
  data: null,                                                                                                                                                                                                                                                                
  error: null,
 retryCount: 0,                                                                                                                                                                                                                                                             
  redirectCount: 0,                                                                                                                                                                                                                                                          
  httpResponse:                                                                                                                                                                                                                                                              
   HttpResponse {                                                                                                                                                                                                                                                            
     statusCode: 404,                                                                                                                                                                                                                                                        
     headers:                                                                                                                                                                                                                                                                
      { 'x-amz-request-id': '185E6989E2461C05',                                                                                                                                                                                                                              
        'x-amz-id-2': '9bp1lRAvcNhQffE6b32lcuuiVKkGUB+P3LfiQ606AlZGOTw9Trh79ql1ue4bge32aHxS6E1OjjM=',                                                                                                                                                                        
        'content-type': 'application/xml',                                                                                                                                                                                                                                   
        'transfer-encoding': 'chunked',                                                                                                                                                                                                                                      
        date: 'Thu, 20 Oct 2016 05:07:11 GMT',                                                                                                                                                                                                                               
        server: 'AmazonS3' },                                                                                                                                                                                                                                                
     body: <Buffer 3c 3f 78 6d 6c 20 76 65 72 73 69 6f 6e 3d 22 31 2e 30 22 20 65 6e 63 6f 64 69 6e 67 3d 22 55 54 46 2d 38 22 3f 3e 0a 3c 45 72 72 6f 72 3e 3c 43 6f 64 ... >,                                                                                              
     streaming: false,                                                                                                                                                                                                                                                       
     stream:                                                                                                                                                                                                                                                                 
      IncomingMessage {                                                                                                                                                                                                                                                      
        _readableState: [Object],                                                                                                                                                                                                                                            
        readable: false,                                                                                                                                                                                                                                                     
        domain: null,                                                                                                                                                                                                                                                        
        _events: [Object],                                                                                                                                                                                                                                                   
        _eventsCount: 3,                                                                                                                                                                                                                                                     
        _maxListeners: undefined,                                                                                                                                                                                                                                            
        socket: [Object],                                                                                                                                                                                                                                                    
        connection: [Object],                                                                                                                                                                                                                                                
        httpVersionMajor: 1,                                                                                                                                                                                                                                                 
        httpVersionMinor: 1,                                                                                                                                                                                                                                                 
        httpVersion: '1.1',                                                                                                                                                                                                                                                  
        complete: true,                                                                                                                                                                                                                                                      
        headers: [Object],                                                                                                                                                                                                                                                   
        rawHeaders: [Object],                                                                                                                                                                                                                                                
        trailers: {},                                                                                                                                                                                                                                                        
        rawTrailers: [],                                                                                                                                                                                                                                                     
        upgrade: false,                                                                                                                                                                                                                                                      
        url: '',                                                                                                                                                                                                                                                             
        method: null,                                                                                                                                                                                                                                                        
        statusCode: 404,                                                                                                                                                                                                                                                     
        statusMessage: 'Not Found',                                                                                                                                                                                                                                          
        client: [Object],                                                                                                                                                                                                                                                    
        _consuming: true,                                                                                                                                                                                                                                                    
        _dumped: false,                                                                                                                                                                                                                                                      
        req: [Object],                                                                                                                                                                                                                                                       
        read: [Function] },                                                                                                                                                                                                                                                  
     _abortCallback: [Function: callNextListener] },                                                                                                                                                                                                                         
  maxRetries: 3,                                                                                                                                                                                                                                                             
  maxRedirects: 10 }                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                             
  Serverless Error ---------------------------------------                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                             
     The specified bucket does not exist  
```

**Comment by lindekaer** [comment]
@njeirath That fixed it, thx for sharing! This can be a temporary workaround for now.

**Comment by str3tch** [comment]
I have the same error.

I deployed to a new account with creds that did not have enough IAM rights, so the deploy failed, and the stack is in "ROLLBACK_COMPLETE" state. It did rollback, and it did delete everything, including the serverless deployment bucket. 

But now I go to deploy same project again (updated credentials), and Serverless is failing because it expects the deployment bucket to be there.

```
serverless deploy --stage chrisd --region ap-southeast-2
Serverless: Packaging service...
 
  Serverless Error ---------------------------------------
 
     The specified bucket does not exist
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
 
  Your Environment Infomation -----------------------------
     OS:                 linux
     Node Version:       4.5.0
     Serverless Version: 1.0.2
``

I think this is a bug - with the fix being it should recreate the deployment bucket if it does not exist.

I can confirm that manually deleting the stack fixes it. But it will often happen that my developers will add resources that they do not have IAM permissions for (they have least privilege rights, and only added on approval). At the moment it's ok to delete the stack but in the future this is not a good workaround.

**Comment by str3tch** [comment]
actually it seems that any time the deployment fails in CFN, you cannot deploy again afterwards.

For instance, this error on first deploy will cause the second deploy to fail with the "bucket does not exist" error.

```
C:\Users\chrisd\Documents\GitHub\uca_ux>sls deploy --stage chrisd --region ap-southeast-2                                                                                                                                                                                    
Serverless: Creating Stack...                                                                                                                                                                                                                                                
Serverless: Checking Stack create progress...                                                                                                                                                                                                                                
............Serverless: Deployment failed!                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                             
  Serverless Error ---------------------------------------                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                             
     An error occurred while provisioning your stack: DNSEntryForStages                                                                                                                                                                                                      
     - No hosted zones named ir-lagrange.com. found.                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                             
  Stack Trace --------------------------------------------      
```

Deploying next time around, I get this:

```

e
  Serverless Error ---------------------------------------                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                             
     The specified bucket does not exist                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                             
  Stack Trace --------------------------------------------   
```

**Comment by stevegula** [comment]
It'd be nice if it at least said that it was the deployment bucket that does not exist. I just spent twenty minutes trying to figure out what happened to my deployment. Because I tied my API to an API Mapping serverless / CF could not delete me stack and serverless errored out on remove. But since CF removed the deployment bucket already any thing I ran failed. As a new-ish user to serverless it took me longer than it should have to figure out what bucket was in question.

**Comment by TomDeMille** [comment]
I have had this and generally it's because there is still a cloudformation script in AWS with 'delete failed'.  

You just need to fix that by manually deleting it.  

In my case I had IAM create role but not IAM delete role, so the cloud formation script was hung up in 'failed delete'.  

I went in as a user with admin rights, manually ran 'delete' on it, waited till it completed and then was able to install  (also I fixed the IAM permissions on the CLI user account)

**Comment by jhabdas** [comment]
PSA to those landing here. You probably manually deleted your Serverless S3 bucket. To solve the problem delete the related CloudFormation as [suggested](https://github.com/serverless/serverless/issues/1877#issuecomment-254971874) by @njeirath and make sure it's deleted [as suggested](https://github.com/serverless/serverless/issues/1877#issuecomment-274121499) by @TomDeMille.

@flomotlik or moderator. Please lock this conversation. A new issue may be opened for those who have other problems.

**Comment by ratbeard** [comment]
I manually deleted my stack in the cloudformation UI and still get this error.  

Giving it a new `stage:` name fixed it.

**Comment by brunocascio** [comment]
I ❤️ u @njeirath

**Comment by shashanktomar** [comment]
Deleting the cloudformation template might not be a good solution. The next deployment will create a new api-gateway deployment with different id, which will change the url(might not matter if you are using cnames).
The better solution which worked for me was:
- go to cloudtrail and select s3 resource to check the deleted bucket name. You don't need this if you have some other way of knowing the bucket name.
- create a bucket with same name.
- retrigger deployment

Looks like serverless use the bucket just for backup. It worked for me.

**Comment by p1Machado** [comment]
I fell into a related issue. My colleague once ago deployed the app at us-east-1 (he removed the bucket, but forgot to remove the CloudFormation stack). Lately we started using sa-east-1. When I decided to deploy the app back to us-east-1, the error message was: "The specified bucket does not exist".

It would be cool if we got clearer messages from serverless.
