### ISSUE TITLE
sls deploy causes 'EMFILE - too many open files' error 

### ISSUE THREAD

**Issue by northerncodemky** [serverless/serverless#3249]
# This is a Bug Report

## Description

* Since upgrading to 1.7.0 the serverless deploy stage is causing an `EMFILE - too many open files error`
* This does not occur in 1.6.1, and updating package.json to reference 1.6.1 resolves this issue
* This does not occur with node 6.9.5, however it is completely reasonable to expect that development teams would be working with the same version of Node as used on the AWS Lambda runtime, and this is exactly the setup we have on our CI servers.
* ***Stack Trace***:
build	15-Feb-2017 08:25:13	
build	15-Feb-2017 08:25:13	> **redacted** deploy **redacted**
build	15-Feb-2017 08:25:13	> sls deploy "--stage" "dev" "--region" "eu-west-1" "--profile" "default"
build	15-Feb-2017 08:25:13	
build	15-Feb-2017 08:25:14	
build	15-Feb-2017 08:25:14	  WARNING: You are running v1.7.0. v1.8.0 will include the following breaking changes:
build	15-Feb-2017 08:25:14	    - Will replace IamPolicyLambdaExecution resource with inline policies -> https://git.io/vDilm
build	15-Feb-2017 08:25:14	    - "sls info" will output the short function name rather than the lambda name -> https://git.io/vDiWx
build	15-Feb-2017 08:25:14	
build	15-Feb-2017 08:25:14	  You can opt-out from these warnings by setting the "SLS_IGNORE_WARNING=*" environment variable.
build	15-Feb-2017 08:25:14	
build	15-Feb-2017 08:25:17	Serverless: Wrote .env file to  **redacted**
build	15-Feb-2017 08:25:17	Serverless: Packaging service...
error	15-Feb-2017 08:25:42	events.js:141
error	15-Feb-2017 08:25:42	      throw er; // Unhandled 'error' event
error	15-Feb-2017 08:25:42	      ^
error	15-Feb-2017 08:25:42	
error	15-Feb-2017 08:25:42	Error: EMFILE: too many open files, open ' **redacted**\node_modules\dynogels\test\schema-test.js'
error	15-Feb-2017 08:25:42	    at Error (native)

Commit [b0df37673bd3a1fac11ccbfa3eb48e3626c0acb1](https://github.com/serverless/serverless/commit/b0df37673bd3a1fac11ccbfa3eb48e3626c0acb1) looks like a potential cause. 

## Additional Data
* ***Serverless Version***
1.7.0
* ***Windows Version***
Windows Server 2012 R2
* ***Node Version***
4.3.2

**Comment by pmuens** [comment]
Thanks for opening @northerncodemky !

How many files do you have in your service?

**Comment by northerncodemky** [comment]
A single handler importing 4 custom sources (we have 9 source files), and 9 dependencies in package.json - none of them are particularly rare and are mostly for accessing AWS resources (e.g. aws-sdk & dynogels),  plus lodash.

**Comment by stevecaldwell77** [comment]
FYI, I ran into this issue too and worked around it by upping my open file limit (I'm on OSX) to 65536 as described here:

  http://blog.mact.me/2014/10/22/yosemite-upgrade-changes-open-file-limit

**Comment by northerncodemky** [comment]
@stevecaldwell77 On Windows here so no such luck

**Comment by msl-kabo** [comment]
Got the same error here on Fedora 25. Running `ulimit -Sn 4096` didn't help. Had to edit `/etc/security/limits.conf` to raise my hard limit to `65536`, log out and log back in, run `ulimit -Sn 65536`, and then I could deploy.

**Comment by HyperBrain** [comment]
Got the same problem on our build servers. 1.7.0 is de facto unusable - changing system settings on the build infrastructure is IMHO not an option at all to "fix" a software issue.
@pmuens This would be a strong reason to provide a 1.7.1 bugfix release outside of the standard release cycle.

**Comment by northerncodemky** [comment]
@HyperBrain @pmuens Agreed. If it is the one-line zip memory use change highlighted could that not be rolled back to allow 1.7.1 to be rolled out whilst a memory-footprint reduction technique that doesn't break the software is explored?

**Comment by pmuens** [comment]
Hey everyone. Sorry for the inconveniences!

We'll look into it!

There are 2 options so that we can get this out of the door ASAP:

1. Switch back to `fs.readFileSync` (like @northerncodemky mentioned above)
2. Use https://github.com/isaacs/node-graceful-fs as a drop in replacement for the fs module (and remove it later on once old Node versions are "officially" outdated)

/cc @eahefnawy

**Comment by pmuens** [comment]
I tried to reproduce this locally, but unfortunately I'm not able to do so.

Has anyone a service we can use to reproduce this? Thanks!

**Comment by pmuens** [comment]
Ok. Finally found a way to reproduce it.

Here are the steps:

1. Use this `serverless.yml` and `package.json` file:

```yml
service: deployment

provider:
  name: aws

package:
  include:
    - node_modules/**

functions:
  foo:
    handler: handler.handler
```

```json
{
  "dependencies": {
    "bluebird": "^3.4.7",
    "chai": "^3.5.0",
    "express": "^4.14.1",
    "jquery": "^3.1.1",
    "lodash": "^4.17.4",
    "mocha": "^3.2.0",
    "serverless-plugin-diff": "^1.3.0",
    "sinon": "^1.17.7",
    "underscore": "^1.8.3",
    "webpack": "^2.2.1"
  }
}
```

2. Spin up a container with the following command:

```bash
docker run --ulimit nofile=20:20 -v $PWD:/app -i -t node:4.3.2 bash
```

3. `cd` into the service and install the dependencies:

**Note:** Those are randomly picked packages

```bash
npm install
```

4. Package the service:

```bash
serverless deploy --noDeploy
```

**Comment by pmuens** [comment]
Quick update:

Using

```javascript
const fs = require('graceful-fs');
```

at the top of `zipService.js` resolves the problem.

**Comment by pmuens** [comment]
Pushed a quickfix PR --> https://github.com/serverless/serverless/pull/3259

would be great if you could test it and see if this resolves the issue.

**Comment by enolan** [comment]
This happens with Node v6.9.5 too. I can reproduce with the `node:6.9.5` Docker image. Using `--ulimit nofile=20:20` didn't work for me though. NPM would fail installing the dependencies and Serverless itself. I launched the container without the option, `cd /app && npm install && npm install -g serverless`, then `ulimit -n 1024`, then `sls deploy --noDeploy`.

**Comment by Stolz** [comment]
same for me. Node 7.5 failing with same error after running `serverless deploy --noDeploy`

    events.js:161
          throw er; // Unhandled 'error' event
          ^
    Error: EMFILE: too many open files, open .../node_modules/serverless/node_modules/lodash/sum.js'

**Comment by scott-martin** [comment]
Any update on this getting patched? Also a blocking issue for me. I was able to get around it by manually updating zipService.js to use graceful-js, but that is obviously not a long-term solution.

**Comment by pmuens** [comment]
@scott-martin This is on the "urgent" list and will be fixed soon!

There's already the `fs-graceful` PR out there (#3259) which resolves the issue. However it introduces other issues with e.g. the usage of the serverless webpack plugin (@HyperBrain discovered this).

Not sure if there's another way right now to fix this in an elegant way.

**Comment by HyperBrain** [comment]
Regarding my experiences with the webpack plugin: With the graceful-fs fix I experienced that the serverless process will just exit to the shell after printing "Packaging service...". Not exactly sure what's happening there exactly.

**Comment by Keksike** [comment]
I also had this problem, but downgrading Serverless to 1.5.1 fixed it for me. Just to let you know.

**Comment by pmuens** [comment]
Thanks for the updates.

The other quick "solution" would be to go back to `readFileSync` (which is used e.g. in v1.5.1). However the downside is that large services will eat up a bunch of memory and so CI / CD systems might suffer (that's why we've changed it to `createReadStream` in the first place).

Other suggestions how to solve this problem are highly welcomed!

**Comment by scott-martin** [comment]
To add some more info from my case. I originally was not using the webpack plugin for this project. Switching to using the webpack plugin actually fixed the issue for me. So I'm not really sure what the discrepancy is between my case and @HyperBrain's, but just thought I would share. It may have something to do with excluding node_modules vs not excluding it.

**Comment by pmuens** [comment]
Ok. Just tested the `graceful-fs` integration once again. Turned out that it was not able to succeed with a really large service.

We'll switch back to `fs.readFileSync` for this release (v1.8). But we'll continue to investigate this issue so that we can switch to a `readStream` again.

**Comment by HyperBrain** [comment]
I verified that 1.8.0 now works again without emitting the EMFILE error.

**Comment by pmuens** [comment]
Thanks for the feedback @HyperBrain 👍 

Glad to hear that the error is resolved!

**Comment by willfarrell** [comment]
For those that are still running into this. Check out https://stackoverflow.com/questions/8965606/node-and-error-emfile-too-many-open-files 

```Dockerfile
FROM node:8

RUN apt-get update -qq \
    && apt-get install -y curl zip python-pip python-dev build-essential \
    && pip install awscli

# Prevent `EMFILE: too many open files, scandir`
# https://stackoverflow.com/questions/8965606/node-and-error-emfile-too-many-open-files
RUN ulimit -Sn 65536
RUN echo "session required pam_limits.so" >> /etc/pam.d/common-session
RUN echo "root soft  nofile 40000" >> /etc/security/limits.conf
RUN echo "root hard  nofile 100000" >> /etc/security/limits.conf

WORKDIR /app
```

**Comment by fsobh** [comment]
Turned out i had multiple projects open in VSCode. after closing all the ones I didn't need, it worked fine.

**Comment by adir1661** [comment]
still having this error, fresh new pc, all versions are updated. anyone faced this issue again?

**Comment by fsobh** [comment]
> still having this error, fresh new pc, all versions are updated. anyone faced this issue again?

Downgrading to SLS version 1.8.0 fixed it for me.

**Comment by fsobh** [comment]
> @fsobh 
> 
> wow thats alot of versions behind. what version you came from?
> 
> i tried it and no luck. just for the info i got windows 11 maybe that is related to the issue?
> 
> 

It's not windows 11 specific, I faced the same issue on windows 10 running the latest version of serverless. At one point I started using docker and installing my modules on the image rather than doing it locally and having sls zipp them up at deploy. This did not give me any issues when deploying with the latest version of serverless

**Comment by adir1661** [comment]
@fsobh i fixed it by exluding the heavier node_modules dependencies in 
```
package:
  exlude:
      # list of biggest modules that are in devdepenedecies and similar
      - node_modules/aws-sdk/**
      - node_modules/serverless-domain-manager/**
      - node_modules/@serverless
      - node_modules/serverless
      - node_modules/java-invoke-local
      - node_modules/tabtab
      - node_modules/snappy
```

**Comment by ThomasEg** [comment]
I find it kinda frustrating that the when searching for an solution for this problem on a new setup(Node 14.17.1, Framework 2.72.2) i'm only finding "Closed"-issues? How can this be closed when it is still happens?

**Comment by adir1661** [comment]
@ThomasEg if you want it to be solved from the source it is might be smarter to open another detailed issue

**Comment by ThomasEg** [comment]
> @ThomasEg if you want it to be solved from the source it is might be smarter to open another detailed issue

It is not a new issue, it's been an issue for the last couple of years. I highly doubt it can/will be solved because i create a new issue. I mostly added my comment for "google history". I'm not even sure it's an issue with Serverless, NodeJS or my setup somehow, but it's still broken and it seems nondeterministic somehow, which makes error reports like mine almost useless....

**Comment by adir1661** [comment]
Totally agree @ThomasEg,

**Comment by pgrzesik** [comment]
Hey @ThomasEg - could you report a fresh issue, ideally with potential reproduction steps? We've been seeing these popping up from time to time but often they were for outdated versions, concering plugins, etc and in general we're covering `EMFILE` bugs with `graceful-fs`, but it seems like there might still be something that we're missing.

**Comment by fsobh** [comment]
This error has officially made serverless UNUSABLE. its been ongoing for the longest time and down grading is NOT an option. all solutions online are only posted for OSX and nothing is out there for windows. Unusable Framework

**Comment by mnapoli** [comment]
@fsobh we do want to help, but as @pgrzesik we need some help identifying the bug.

Are you able to post a use case that reproduces it?

**Comment by ThomasEg** [comment]
@mnapoli It's very hard to provide you with any sort of information on how to reproduce this bug. It seems, to me at least, non-deterministic. You can have the issue, upgrade or downgrade some component and the bug disappears. Then suddenly it re-appears and you can roll back to the previous version(which previously failed) and then everything works again. I think it is almost impossible to give you the information you request/need to fix this issue:-(

**Comment by adir1661** [comment]
which lead to the question: are the team responsible of serverless can deal with unreproducible issues that ruin its core technology and are critical for most of the users to the level of leaving this framework entirely?

**Comment by fsobh** [comment]
> which lead to the question: are the team responsible of serverless can deal with unreproducible issues that ruin its core technology and are critical for most of the users to the level of leaving this framework entirely?

The issue here was serverless-offline package. The second I removed it, everything worked flawlessly. For some reason, when you tell your yaml file to exclude it at deployment, it still tries to include it.
