### ISSUE TITLE
Schedule event inputs are ignored

### ISSUE THREAD

**Issue by bartkummel** [serverless/serverless#3886]
# This is a Bug Report

## Description

For bug reports:
* **What went wrong?**
  I added an `events` section to my function

  ```json
  functions:
    produce:
      handler: produce.handler
      description: Blah blah.
      role: arn:aws:iam::...
      memorySize: 128
      vpc:
        securityGroupIds:
          - sg-12345
        subnetIds:
          - subnet-1
          - subnet-2
          - subnet-3
      events:
        - schedule: rate(1 minute)
          enabled: true
          name: update-schedule
          description: Updates the thing every minute
          input:
            bucket: my-bucket
            directory: some-directory
  ```
  A "rule" was created in AWS CloudWatch. But the inputs I defined were not in the rule. 
* **What did you expect should have happened?**
  I expected the inputs to be in the "Constant (JSON text)" part of the CloudWatch rule 
* **What was the config you used?**
  See above
* **What stacktrace or error message from your provider did you see?**
  I didn't see any error, apart from the error in my lambda function because of the missing input.

## Additional Data

* ***Serverless Framework Version you're using***: 1.16.1
* ***Operating System***: My laptop runs MacOS, my lambda gets deployed by Codeship. My Codeship build runs on a docker image, based on `lambci/lambda:build-nodejs`
* ***Stack Trace***: N/A
* ***Provider Error messages***: N/A

**Comment by nafetswirth** [comment]
I think I have the same problem after updating to 1.16.1 for an event that uses a dynamoDB stream.

It creates the stream and the serverless state shows the Stream but it doesn't create the eventMapping

[Here's a barebones example with the build that serverless creates if that helps](https://github.com/nafetswirth/serverless-example)

Please let me know if this should be a separate issue and I'll open one

**Comment by pmuens** [comment]
Hey @bartkummel thanks for opening! 👍 

Just looked through your `serverless.yml` file and it looks like your `schedule` event definition is not correct. You can see full examples in the docs here:

https://serverless.com/framework/docs/providers/aws/events/schedule/

Closing this for now since updating the config should resolve this problem.

@nafetswirth it looks like your indentation is also incorrect. You can find examples for the `stream` event here:

https://serverless.com/framework/docs/providers/aws/events/stream/

Let us know if you still face any issues 👍

**Comment by bartkummel** [comment]
Hi @pmuens , thanks for looking into this! I still have some comments:

- The example you linked to is a bit hidden. I was looking for an example with inputs. Although the example you linked to has inputs, the example is in a section on another topic. I think inputs deserve a section of their own, with a dedicated example. That would be a good improvement of the docs.
- Apparently, there are two different syntaxes of `schedule`: an "inline" variant, with only the rate, as well as a "full" variant, with all other options available. I think mentioning this explicitly would also improve the docs.
- I think it's wrong that serverless doesn't complain about the wrong indentation. It just fails silently by skipping the `schedule`. It would be better if there was at least a warning about a part of the YAML file being invalid. In my opinion serverless could also just exit with a proper error description on such an error.

**Comment by nafetswirth** [comment]
Hi @pmuens you were right and it worked after fixing the indentation although i was sure i haven't changed anything from before and it worked back then but that's every bug right :) 

Sorry for the noise and thanks for the help.

**Comment by pmuens** [comment]
Thanks for the in-depth feedback on the docs @bartkummel 👍 really appreciate that!

I agree. Having this mixture between the "simple" and "complex" syntax can be confusing.
We're always looking for ways how we can improve the docs (doc update PRs are really welcomed).

We already merged the first PR where the check for the indentation is applied to the `http` event (https://github.com/serverless/serverless/pull/3846). Maybe we should extend this to the other event sources as well.

> Hi @pmuens you were right and it worked after fixing the indentation although i was sure i haven't changed anything from before and it worked back then but that's every bug right :)

@nafetswirth great to hear that this fixed your problem 👍

**Comment by laurenfb** [comment]
Agreed that a warning on incorrect indentation would be super useful for this!
