### ISSUE TITLE
Environment variables not updating in new lambda function version

### ISSUE THREAD

**Issue by aliatsis** [serverless/serverless#4638]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
New environment variables are not deploying to new function version for AWS Lambda.
I've verified that the new variables are properly set inside the CloudFormation stack template.
I've also ran every variation of deploy (with `-p`, with `-f`, with `--force`, with `--update-config`, and with code changes). My base use case is to `sls package` first, then deploy with `-p`

* What did you expect should have happened?
Changing or adding environment variables in serverless.yml should update environment variables in lambda console for the corresponding function version when deployed.

* What was the config you used?
```
service:
  name: foo-service
  awsKmsKeyArn: ${ssm:/infra/lambda-env-kms-key-id}

frameworkVersion: "^1.25.0"

functions:
  foo-service:
    name: ${self:custom.stageNames.${self:provider.stage}, self:custom.defaultName}
    handler: dist/lambda.handler

provider:
  name: aws
  stage: ${opt:stage, self:custom.defaultStage}
  region: us-east-1
  profile: serverless
  deploymentBucket:
    name: ${ssm:/infra/serverless-deployment-bucket}
    serverSideEncryption: aws:kms
    sseKMSKeyId: ${ssm:/infra/serverless-deployment-bucket-kms-key-id}
  
  # service function settings
  runtime: nodejs6.10
  memorySize: 1024
  timeout: 30
  environment:
    SERVERLESS_STAGE: ${self:provider.stage}
    SERVERLESS_ALIAS: ${self:provider.alias}
    NODE_ENV: ${ssm:/infra/NODE_ENV}
    MY_NEW_ENV_VAR: ${ssm:/infra/foobar}
  vpc:
    subnetIds:
      - ${ssm:/infra/lambda-subnet}
    securityGroupIds:
      - ${ssm:/infra/lambda-sg}

custom:
  defaultName: ${self:service}__${self:provider.stage}
  defaultStage: staging
  defaultRegion: us-east-1
  stageNames:
    staging: ${self:service}
    prod: ${self:service}

package:
  include:
    - dist/**
    - node_modules/**
    - '!**/*.d.ts'
    - '!**/*.test.js'
    - '!**/*.spec.js'
    - '!**/__tests__/**'
  exclude:
    - '**'

plugins:
  - serverless-pseudo-parameters
  - serverless-aws-alias
```
* What stacktrace or error message from your provider did you see?
No error message. Package and Deploy were successful.

Similar or dependent issues:
* https://github.com/HyperBrain/serverless-aws-alias/issues/91

## Additional Data

* ***Serverless Framework Version you're using***:
1.25.0
* ***Operating System***:
Mac High Sierra locally and Ubuntu in CircleCI
* ***Stack Trace***:
None
* ***Provider Error messages***:
None

**Comment by BDQ** [comment]
I've can confirm this issues with 1.25.0 - if the lambda's code doesn't change the function deploy is skipped so the new env var isn't setup. Changing the code, the env var will be added.

**Comment by Sly777** [comment]
I tried with --force but It didn't work. @BDQ @horike37 

serverless 1.26

**Comment by nullflux** [comment]
I can also confirm this issue with 1.26.0

**Comment by hassankhan** [comment]
Had a quick look through the code, the place where this is likely occurring is [here](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/deploy/lib/checkForChanges.js#L77).

**Comment by zimny** [comment]
+1

**Comment by jake-lambert-volusion** [comment]
When updating `timeout` or `memorySize`, the updated values are reflected in the Cloudformation stack template and reflected on the `$latest` version in the AWS Lambda console, but if I navigate to the most recent version directly, they are not.

**Comment by avi-beetul** [comment]
+1

**Comment by PouriaSterling** [comment]
+1

**Comment by jonasof** [comment]
When I tried to deploy a single function with --function, with some environment variable as integer (example: VARIABLE: 123), I got:

```
* InvalidParameterType: Expected 
params.Environment.Variables['VARIABLE'] to be a string.
```

And the deploy failed. After changing the integer variable to string '123', the `sls deploy` has updated the environment variables correctly.

**Comment by simlu** [comment]
Similar issue. This is pretty severe for us. Anyone figured out what is going on here?

**Comment by MacMcIrish** [comment]
I've noticed that when updating environment variables in the serverless config:
```
environment:
  VAR: ${env:VAR}
```
WILL update the lambda function environment variables, but references like
```
environment:
  VAR: { "Ref": MyResource }
```
will NOT update the lambda function environment variables.

**Comment by ctala** [comment]
This happened to me today. Is there any workaround on how to solve it ?

**Comment by danepowell** [comment]
I encountered this too. In my case, it seems that if you modify a variable via the Lambda console and then re-run a serverless deploy, it will _not_ overwrite the value you set in the console. But if you then update any variable at all in the serverless config, it will overwrite all values in Lambda.

**Comment by saumilsdk** [comment]
+1

**Comment by sverraest** [comment]
Encountered the same issue today but even changing the code will not add / update the parameter I added in environment.

**Comment by markddavidoff** [comment]
+1

**Comment by cub33** [comment]
+1

**Comment by chrisyorkston** [comment]
Any update on this?

**Comment by mmuallem** [comment]
+1.

Happened to me today updating a Lambda. The function logic was updated, but not the environment variables.

MacOS Mojave 10.14.1. Serverless v. 1.33.2

**Comment by dschep** [comment]
Hmm. Are people only having issues with `Ref` based env vars as @MacMcIrish mentioned or with normal variahbles too? @MacMcIrish, I'm not surprised `Ref` causes an issue since the code compares the CloudFormation template to decide to redeploy or not. you can always use `sls deploy -f` to deploy regardless of the template not being changed. That being said, it absolutely shouldn't be necessary and we'll ook into fixing this. Should be doable by having the cfn template normalization code (currently it serves to remove references to s3 buckets since those change every deploy/package) to also replace refs with a random value so the comparison finds a change in the deployment.

**Comment by mmuallem** [comment]
@dschep, our variables are loaded through a file, from a config YAML file

**Comment by dschep** [comment]
Hey folks, I've created https://github.com/dschep-bug-repos/sls-4638 to try to reproduce this bug, but to no avail. Do the steps in the readme cause the bug for any of you? If not, what differences does your setup have that you could make to cause my repo to reproduce the bug? Let me know here or make a PR to that repo with a change that causes the bug to occur.

**Comment by DCazier** [comment]
For what it's worth, we were having this problem in our organization too. In our serverless.yml file I decided to change the 'timeout' property of one our lambdas from 10s to 15s. Deployed that changed. All env variable changes after that began to deploy as normal. 

Seems to have solved our issue. Not sure what caused this to begin with, but hopefully this helps in the debugging or to get people unblocked.

**Comment by usamayousuf13** [comment]
having similar issue. Environment variables are showing null in lambda console when i try to pass the cloudformation parameters to my lambda environment variables. I am attaching a chunk of my CF template just to elaborate. 



`"Parameters": {
    "userIdParameter": {
      "Description": "some userId here",
      "Type": "String"
    }
}
"createLambdaFunction": {
      "Type": "AWS::Lambda::Function",
      "Properties": {
        "Code": {
          "S3Bucket": "some-s3-bucket",
          "S3Key": "deployment-package.zip"
        },
        "Environment": {
          "Variables":{
            "userId": {
              "Ref": "userIdParameter"
            }
          }
        },
        "Handler": "index.handler",
        "Role":  "roleArn here",
        "Runtime": "nodejs8.10",
        "Timeout": 30
      }
    }`

**Comment by hsz** [comment]
I met the same issue when deploying whole package with `sls deploy` and even `--force` didn't update the environment variables.
When deploying specific function with `--force` - it works, but that's not a perfect solution.

Anyway - as a workaround I've figured out, that setting another extra env variable called i.e. `BUILD_TIME` with a timestamp that changes every time - all variables are set properly.

**Comment by veromarchand** [comment]
I am having a similar problem (also using the $file syntax, under the custom section, which is then used to generate the ENV variables), my env variables won't take in AWS. Works fine when running serverless locally. 

Updating the code "works", as in, I can see the new code being executed, but environment variables are always empty.

Any suggestions?

**Comment by ahmed-abdulmoniem** [comment]
Still happening

**Comment by markbreal** [comment]
I thought we were suffering this, in particular with variables set using `Ref:`, but it turned out that CloudFormation had somehow lost it's grip on the stack we were referencing.  CloudFormation was returning the Id of a previous incarnation of the same stack.  That is at least consistent with what CloudFormation Resources tab shows - but they're both wrong!  I'm raising a separate bug with AWS about this.

This was a non-production CF stack that had been deleted and recreated a few times as we got to grips with the deployment process, and sometimes got stuck in the dreaded UPDATE_ROLLBACK_FAILED state and deleted it rather than waiting.

**Comment by trmaphi** [comment]
I got the same problem when deploy a single function using `sls deploy -s dev -r ap-southeast-1 -f api`. The environment variables in serverless.yml under `provider.environment` doesn't update in aws.

This behavior is not expected in our development when we have numerous of lambda functions.

**Comment by cyberfox1** [comment]
Just happened to me to.

**Comment by medikoo** [comment]
This would most likely be fixed with solution proposed here: https://github.com/serverless/serverless/issues/6243#issuecomment-501668041 (just a note, to make both issues connected)

**Comment by boyvanduuren** [comment]
@medikoo I'm actually not too sure whether that's the case. Myself, and a few other people that reported in this thread before me actually don't even see the environment variable(s) update when forcing a deployment. I can force using `--force`, or even by doing a code change to trigger deployment, but the environment variables are not changed.
The cloudformation template did change though, so this might not even be a bug with serverless itself?

**Comment by medikoo** [comment]
@boyvanduuren yes, it's probably the case, that it requires full stack update (and not just a function update), and that's best if signaled by the framework.

**Comment by pmuens** [comment]
Hey everyone, I too looked into this today and tried to reproduce this.

(Un)fortunately I couldn't reproduce this problem on my end. Can someone post a step-by-step guide which outlines how this bug can be surfaced? Please make sure to use the most recent Serverless version as we've fixed quite some problems after the initial report in 2018.

**Comment by boyvanduuren** [comment]
@pmuens I've not been able to get a stack in this state purposefully. We've always encountered this on stacks that were running for a while and were update at least a few times. Spent a good few hours on trying various things to get a stack into this state, but didn't succeed.

**Comment by pmuens** [comment]
Thanks for following-up @boyvanduuren :+1:

In that case I'll close this issue for now since it seems to be non-deterministic and hard to reproduce. @aliatsis feel free to re-open it if you see this bug again and can shed some light into the reproduction.

**Comment by duy9403** [comment]
@pmuens 
I managed to reproduce the problem.
```
     OS:                     linux  # (Ubuntu subsystem on Windows 10)
     Node Version:           8.12.0
     Serverless Version:     1.47.0

# Create dir and init serverless
sls create -t aws-nodejs-typescript

# Install npm packages
npm i

# Deploy serverless
sls deploy
```

Now modify `serverless.yml`, add `environment` to function:
```
    enviroment:
      USE_AWS_SECRETS_MANAGER: true
      AWS_SECRET_ID: /foo/bar
```

`serverless.yml` looks like this:
```
service:
  name: aws-nodejs-typescript

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
    enviroment:
      USE_AWS_SECRETS_MANAGER: true
      AWS_SECRET_ID: /foo/bar
```

Now deploy by `sls deploy`, even with `--force`, the lambda still doesn't have env var.
![image](https://user-images.githubusercontent.com/33267089/61532688-e7740700-aa2a-11e9-8b74-4355c4422102.png)

**Comment by duy9403** [comment]
I was commenting that I could reproduced the problem, but actually I misspelt `enviroment`, I deleted the original comment. I apologize for the notification.

**Comment by divyenduz** [comment]
I can reproduce this in the following scenario. If I change the environment variable from the AWS Console UI, then `sls deploy` doesn't change it anymore. Was the experience same for any of you?

**Comment by rooleek** [comment]
Guys, 
this is stil reproducable. Any workarounds?

**Comment by markbreal** [comment]
> I can reproduce this in the following scenario. If I change the environment variable from the AWS Console UI, then `sls deploy` doesn't change it anymore. Was the experience same for any of you?

@divyenduz my understanding is that `serverless` works via CloudFormation, so if you work directly via the AWS Console neither CloudFormation nor `serverless` will find anything to do, although CloudFormation drift detection _might_ show up something. I don't think what you describe is related to this issue.

**Comment by divyenduz** [comment]
@markbreal Thanks for the answer, yes, I agree with that. I also noticed that `--force` still overrides the env vars, which is the expected behavior.

**Comment by xaun** [comment]
Yep still reproducible. Since editing a environment variable through the AWS console, serverless.yml updates to that variable are no longer being received.

**Comment by medikoo** [comment]
If you think there's a bug in existing version of a framework, please open an bug report respecting all its template remarks

**Comment by aproblemsolver** [comment]
> I've noticed that when updating environment variables in the serverless config:
> 
> ```
> environment:
>   VAR: ${env:VAR}
> ```
> 
> WILL update the lambda function environment variables, but references like
> 
> ```
> environment:
>   VAR: { "Ref": MyResource }
> ```
> 
> will NOT update the lambda function environment variables.

Any way to fix this behavior?

**Comment by aproblemsolver** [comment]
Hi @pgrzesik, I have a CloudFormation template with parameters and a global section. I am passing environment variables from the global section.
Also, the actual values of these env vars are stored in Secret manager. I fetch them in a code build environment section using `<Secret name or ARN>:<Key>` combination.
So they become available in code build runtime. From there, I use `sed` commands to replace the string variables in my template file.
The deployment is done using sam build and sam deploy in the `buildspec` file.

**Comment by rdsedmundo** [comment]
Hitting this 4 years later. Edited something on the AWS console one-off for testing, and Serverless Framework won't override it again even upon doing a full `sls deploy` of the service again.

**Comment by medikoo** [comment]
@rdsedmundo can Framework do something about it? I think that at any time you try to do updates manually and not via proper CF update, there's a risk of going out of sync.

CF update simply does comparison against the previously deployed state, and assumes there were no changes done on the side to related resources. Framework trusts that as well.

To mitigate the scenarios you mention in broad scope, Framework will have to confirm on every single property as configured in CF stack and apply side AWS SDK updates if there's a mismatch. Such will be killing performance-wise, and I don't see it possible to achieve maintenance-wise. 

The only real solution is: do not update resources as deployed with stack manually, and if you do, mind the consequences

**Comment by rdsedmundo** [comment]
That makes sense considering the CF stack is drifted now that you said it. I believe the current behavior makes sense.

**Comment by edrichhans** [comment]
What seems to work for me is temporarily adding a new environment variable in my `serverless.yml` file and just remove it after deploying. This triggers CF to replace all environment variables in the lambda function

**Comment by fahadsiddiqui** [comment]
+1
