### ISSUE TITLE
Improve documentation for creating plugins

### ISSUE THREAD

**Issue by traviswimer** [serverless/serverless#4935]
# This is a Feature Proposal

## Description

* *What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.*

I have been trying to wrap my head around creating a Serverless plugin, but I've found it to be very confusing. Mainly I am confused by the `lifecycleEvents` and the `hooks`.

A few things I think would be helpful to add to the docs:
1. A chronological list describing each lifecycleEvent.
2. More realistic examples of plugins. The blog posts linked in the docs (https://serverless.com/blog/writing-serverless-plugins/) are a decent overview, but don't provide enough detail for creating a useful plugin.
3. **MOST IMPORTANTLY**: Documentation on the `pluginManager`. I've tried to learn from the code in other plugins, but none of the ones I've looked at use the `pluginManager`. This is problematic, since it makes their lifecycleEvents mostly useless. The best (and only) resource I've come across explaining the `pluginManager` is this blog post:
https://serverless.com/blog/advanced-plugin-development-extending-the-core-lifecycle/
If nothing else, it would be nice if a link to this was added in the docs. It took me a while to figure out why I couldn't hook to another plugin's events, but it ended up being because those events were never fired, since the code just called methods rather than using the `pluginManager`.

* *If there is additional config how would it look*
N/A

Similar or dependent issues:
nope

## Additional Data

* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

**Comment by HyperBrain** [comment]
@traviswimer Here's my Gist for the lifecycle events - https://gist.github.com/HyperBrain/50d38027a8f57778d5b0f135d80ea406. I keep it up to date and it should reflect the currently available hooks+events.

> but none of the ones I've looked at use the pluginManager
That's not really true. Please check [serverless-webpack](https://github.com/serverless-heaven/serverless-webpack). I implemented a fully exposed plugin lifecycle there, so that other plugins can easily hook into serverless-webpack.

When I rewrote the event subsystem in Serverless and added full lifecycle support via `pluginManager.spawn()` and command entrypoints I had exactly this full plugin flexibility in mind. So serverless-webpack is the (imo right now the only one) reference on how to provide a plugin that exposes hookable events and uses entrypoints, sublifecycles, etc. as it is intended.

However, I have to agree, that a full documentation that includes everything is yet missing. However I've written two blog posts in the past (serverless blog) that explain the newly introduced mechanisms. You can look them up and let me know, if that's useful.

BTW: I'd also volunteer to write a more complete blog or some kind of documentation.

**Comment by HyperBrain** [comment]
Just recognized that you already posted one of my blog posts above 😀 . The second one completes that (and is a bit older) and concentrates more on the lifecycles themselves.

**Comment by traviswimer** [comment]
Thanks for the response! I started looking through the source of *serverless-webpack* and your other blog post. They've been really helpful.

A couple other "pain points" I've noticed (and I'm still not entirely sure about.):
- When should you use `lifecycleEvents` and when should you use `pluginManager.spawn()`? Or I guess maybe plugin best-practices in general. I get the impression that a decent amount of plugins are not using events as intended. (not using `pluginManager`/events not ever firing)
- If two plugins hook to the same event, which function will be called first?
- If you hook to an event, is your function called before or after the original handler? Or is it async and runs at the same time? If it's not async, why do both the `before` and `after` events need to exist?

Also, I had a random idea that my be useful for clarify events. It would be cool if Serverless had a flag to turn on logging when every event occurs (maybe using SLS_DEBUG). This would help a lot with understanding when (and if) events are invoked.

**Comment by HyperBrain** [comment]
Hi  @traviswimer ,

> If two plugins hook to the same event, which function will be called first?

The order is sepcified by the order, the plugins appear in the `serverless.yml`'s plugin list. Plugins listed first will be called first.

> If you hook to an event, is your function called before or after the original handler? 

You only can hook with `before:*` and `after:*` into another plugin. As the preposition states, your code will be called at the specified time. All hooks must return a promise that is awaited before the next hook or the event definition is executed to make sure that the chain is deterministic and the previous hook has finished (possibly changing the state of the serverless instance). If you define a hook without any preposition, that means that you _define_ the lifecycle event and do not hook into it. Only one plugin shall define a specific lifecycle event - hooked plugins must only hook with the prepositions.

That's also how the sublifecycle (`webpack:*`) works in `serverless-webpack` and why it can expose new events. It defines the events, so that others can hook them.
Spawn is used to enter the lifecycle events, because only that triggers the event notifications within pluginManager. So instead of calling `this.myFunctionality()' in a plugin, which would be decoupled from the event system, you use spawn('myPlugin:myFunctionalityEvent') to run through the complete event lifecycle of myFunctionality, including all registered hooks and the definition itself (e.g. `hooks: { 'myModule:myFunctionality' : () => BbPromise.bind(this).then(() => this.myFunctionality()); }`)

> It would be cool if Serverless had a flag to turn on logging when every event occurs (maybe using SLS_DEBUG).

I already added that for commands/entrypoints. I agree that the events themselves would add an additional useful level of detail here. However, I'd not enable it with SLS_DEBUG but with a completely separate debug whatever switch, because event logging will be _huge_ !

I'll try to write on an article that explains the whole mechanism in one document with examples. Examples are IMO a very important key here, because you'll get it much faster and easier when having some hands-on available.
A big thank you for listing the pain points :thumbsup: - for me, it was not exactly clear what has to be mentioned and explained in a perfect guide.

**Comment by alexander-alvarez** [comment]
Would be great if this information (and more) made it to the guides.

Currently Plugins are under the provider sections -- I didn't even know they existed until I used the search box, because I was working under the kubeless provider (which doesn't have a plugins section)
https://github.com/serverless/serverless/blob/master/docs/providers/aws/guide/plugins.md
https://github.com/serverless/serverless/blob/master/docs/providers/azure/guide/plugins.md
Maybe they should be brought up a level since they are a more general concept.

The information you provided here and in the gist is on the right track.
Some other things I'd like to know having just started with serverless this week but used other tools with plugin systems:

- What are all of the native hooks?
- What are the signatures of the native hooks?
    - e.g. What is the `serverless` object passed into the plugin constructor?
> The serverless instance which enables access to global service config during runtime is passed in as the first parameter to the plugin constructor.

  -  So does this mean the `serverless` object has the properties defined in the `serverless.yml`? Some sort of JS/ESDoc would be great for this.
- How do I test a plugin?

The local plugin development could be clarified:
- `.serverless_plugins` -> can this be customized? I'd rather not have plugin source files a hidden folder
> The plugin will be loaded based on being named  `custom-serverless-plugin.js` or `custom-serverless-plugin\index.js` in the root of `.serverless_plugins` folder.

- What does this mean? Do I literally have to define a file `.serverless_plugins/custom-serverless-plugin.js` or `.serverless_plugins/custom-serverless-plugin/index.js`, because that's what it makes it sound like? 
Or is it trying to say plugins can either be exported by a file or a module?
e.g. `.serverless_plugins/<my-plugin-name>.js` or `.serverless_plugins/<my-plugin-name>/index.js`

I think that's all I have to contribute from my 1 week using the framework

**Comment by pmuens** [comment]
Closing in favor of https://github.com/serverless/serverless/issues/3651
