### ISSUE TITLE
devDependencies aren’t excluded with npm 7

### ISSUE THREAD

**Issue by birsi** [serverless/serverless#9101]
With `npm 7.6.2`, `serverless` fails to exclude `devDependencies` from `package.json`.

Directly relating to: https://github.com/serverless/serverless/issues/8500

<details>
<summary><code>serverless.yml</code></summary>

```yaml
service: serverless-starter

provider:
  name: aws
  runtime: nodejs4.3

functions:
  single:
    handler: single.handler
    events:
      - http:
          path: single
          method: get
      - http:
          path: single
          method: post
  multiCreate:
    handler: multiCreate.handler
    events:
      - http:
          path: multi/create
          method: get
  multiShow:
    handler: multiShow.handler
    events:
      - http:
          path: multi/show/{id}
          method: get
```

</details>

<details>
<summary>Steps to reproduce</summary>

Incorrect behaviour with `npm 7.6.2` including full `devDependencies` in `node_modules` with `185M` 

```
# Clone the official starter
git clone https://github.com/serverless/serverless-starter
cd serverless-starter

# Switch to Node 15 which comes with npm 7 (using https://github.com/tj/n)
sudo n 15
npm --version
# → 7.0.8

# Add a devDependency
npm i --save-dev serverless
npx serverless version
# → Framework Core: 2.11.1 (local)
# → Plugin: 4.1.2
# → SDK: 2.3.2
# → Components: 3.3.0

# Package the function
npx serverless package
du -h .serverless/serverless-starter.zip
# → 37M	.serverless/serverless-starter.zip

du -h .serverless/serverless-starter/node_modules
# → 185M node_modules
```
</details>

<b>Installed version</b>

```
Framework Core: 2.29.0 (local)
Plugin: 4.5.0
SDK: 4.2.0
Components: 3.7.3

nodejs: 14.16.0
npm: 7.6.2

System Version: macOS 11.2.2 (20D80)
Kernel Version: Darwin 20.3.0
```

**Comment by pgrzesik** [comment]
Hello @birsi, thanks a lot for reporting. @medikoo do you know the reason why the original #8500 was closed?

**Comment by medikoo** [comment]
> Hello @birsi, thanks a lot for reporting. @medikoo do you know the reason why the original #8500 was closed?

It was assumed as fixed with https://github.com/serverless/serverless/pull/8505 Wasn't it ?

**Comment by pgrzesik** [comment]
Sorry @medikoo - I've just verified on the latest `2.29.0` and I cannot reproduce the original issue so it seems like the issue has been fixed correctly.

@birsi - I see that the example you provided for reproducing is the exact same as in #8500 - I cannot reproduce the issue with it. Are you certain that you're on the latest version of Serverless Framework or at least on `2.12.0` where it was fixed(https://github.com/serverless/serverless/blob/master/CHANGELOG.md#2120-2020-11-20)?

**Comment by birsi** [comment]
Hi! Thanks for looking into the issue! I updated the exact repro scenario (just confirmed and fixed the version numbers) and now re-tried from scratch. Same outcome: still the dev dependencies are bundled which resolves to

```
du -hs .serverless/serverless-starter/node_modules
185M	.serverless/serverless-starter/node_modules
```

**Comment by pgrzesik** [comment]
Thanks @birsi - I tried once again and I cannot reproduce the issue. @medikoo Do you think you could try reproducing it on Mac? That's the only difference that I see in my setup (I'm on Linux).

**Comment by birsi** [comment]
Thank you @pgrzesik! Very odd indeed. I will ask my team to reproduce it for an additional confirmation as well.

**Comment by medikoo** [comment]
@birsi I also cannot reproduce it on macOS. Created even reproduction case (with all deps installed and versioned) here: https://github.com/medikoo/test-serverless/tree/9101-case

And when working with it, outcome is as follows:

```
% npm -v
7.6.3

% node -v
v14.16.0

% npx serverless --version
Framework Core: 2.30.3 (local)
Plugin: 4.5.1
SDK: 4.2.0
Components: 3.7.4

% npx serverless package
Serverless: Configuration warning at 'provider.runtime': should be equal to one of the allowed values [dotnetcore2.1, dotnetcore3.1, go1.x, java11, java8, java8.al2, nodejs10.x, nodejs12.x, nodejs14.x, provided, provided.al2, python2.7, python3.6, python3.7, python3.8, ruby2.5, ruby2.7]
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:  
Serverless: Deprecation warning: Starting with next major, Serverless will throw on configuration errors by default. Adapt to this behavior now by adding "configValidationMode: error" to service configuration
            More Info: https://www.serverless.com/framework/docs/deprecations/#CONFIG_VALIDATION_MODE_DEFAULT
Serverless: Deprecation warning: Resolution of lambda version hashes was improved with better algorithm, which will be used in next major release.
            Switch to it now by setting "provider.lambdaHashingVersion" to "20201221"
            More Info: https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2
Serverless: Deprecation warning: Starting with next major version, API Gateway naming will be changed from "{stage}-{service}" to "{service}-{stage}".
            Set "provider.apiGateway.shouldStartNameWithService" to "true" to adapt to the new behavior now.
            More Info: https://www.serverless.com/framework/docs/deprecations/#AWS_API_GATEWAY_NAME_STARTING_WITH_SERVICE
Serverless: Packaging service...
Serverless: Excluding development dependencies...

% du -h .serverless/serverless-starter.zip
 80K	.serverless/serverless-starter.zip

 % du -hs node_modules                           
186M	node_modules

% ls -la .serverless 
total 264
drwxr-xr-x   6 medikoo  staff    192 Mar 17 12:20 .
drwxr-xr-x  16 medikoo  staff    512 Mar 17 12:20 ..
-rw-r--r--   1 medikoo  staff   2077 Mar 17 12:20 cloudformation-template-create-stack.json
-rw-r--r--   1 medikoo  staff  18192 Mar 17 12:20 cloudformation-template-update-stack.json
-rw-r--r--   1 medikoo  staff  78709 Mar 17 12:20 serverless-starter.zip
-rw-r--r--   1 medikoo  staff  27888 Mar 17 12:20 serverless-state.json
```

Also note there's no `.serverless/serverless-starter/node_modules` folder as in your case.

**Comment by pgrzesik** [comment]
Thanks @medikoo - I have the exact same results on my machine.

**Comment by birsi** [comment]
Hey all! A quick update from our investigation so far: We could boil it down to `asdf`. When working with `npm 7` in conjunction with `asdf`, the issue is reproducible. (It works with `npm 6` though.)

I updated the _reproduction scenario_ in my initial description. Not sure how we should move forward from here, but the two options we see for us in our environment are now: 

1) sticking to `asdf` and use `serverless-jetpack` 
2) remove `asdf` and switch to `nvm`

**Comment by medikoo** [comment]
@birsi and do you understand where you get `.serverless/serverless-starter/node_modules` from ? It's not created when packaging service as in your example, while you're stating that this directory is created (this facts do not match up)

**Comment by birsi** [comment]
Yes, thank you and sorry that information was confusing. It was only about the unzipped `serverless-starter/.serverless/serverless-starter.zip` --> `.serverless/serverless-starter/node_modules` to compare it to the unzipped `node_modules` and show that they result in the same size without any exclusions. I hope this clears it up a bit.

**Comment by medikoo** [comment]
> When working with `npm 7` in conjunction with `asdf`. the issue is reproducible

It'll be good to coin, what exactly is responsible for reproducing the issue.

Fix on our side, was simply about adding [`--all`](https://github.com/serverless/serverless/pull/8505/files) param to `npm` command. Is it that `npm` behaves differently in env as setup by `asdf`?

Anyway, it's important to note that this issue will definitely be gone once https://github.com/serverless/serverless/issues/8586 is addressed, and addressing this, is on our priorities list.

**Comment by pgrzesik** [comment]
I think this issue might be related to the one I'm currently investigating: https://github.com/serverless/serverless/issues/9134

So far I've discovered an unexpected behavior of `npm ls` when `NODE_ENV=production` is present and `dev/prod` flags are involved. Do you happen to know if `asdf` is setting `NODE_ENV` to some specific value?

**Comment by birsi** [comment]
Quick update. Just tried `2.31.0 (2021-03-23)` including #9134, but unfortunately no effect and still the same outcome, resulting in no exclusion of the `devDependencies` when using `asdf`. 

I'm afraid I can't answer on your question regarding `asdf` and `NODE_ENV` as I could not look into it in more detail yet.

```
sls -v
# → Serverless: Running "serverless" installed locally (in service node_modules)
# → Framework Core: 2.31.0 (local)
# → Plugin: 4.5.2
# → SDK: 4.2.2
# → Components: 3.7.6

du -h .serverless/serverless-starter.zip
# → 38M	.serverless/serverless-starter.zip
```

**Comment by pgrzesik** [comment]
Hello @birsi - did you manage to resolve that problem on your side? Did you have a chance to check if the problem persist when NOT using `asdf`? I've also tried to reproduce it with `asdf` on my machine but it works as expected.
